"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { BadgeCheck, ExternalLink, Loader2, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { API } from "@/lib/api";

type Listing = { id:number; slug:string; unitId:number; status:string; listingType:string; headline:string; publisherUserId:number; publishedAt?:string; expiresAt?:string; suspensionReason?:string };
export default function PropertyListingManagementPage() {
  const [items,setItems]=useState<Listing[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number>();
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await API.get("/property/listings/admin?size=50");setItems(data.content||[]);}catch{toast.error("Could not load property listings");}finally{setLoading(false);}},[]);
  useEffect(()=>{
    // This effect intentionally starts synchronization with the authenticated admin API.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  async function moderate(item:Listing){const suspending=item.status!=="SUSPENDED";let reason:string|undefined;if(suspending){reason=window.prompt("Why is this listing being suspended?")?.trim();if(!reason)return;}setBusy(item.id);try{await API.put(`/property/listings/admin/${item.id}/moderation`,{action:suspending?"SUSPEND":"REACTIVATE",reason});toast.success(suspending?"Listing suspended":"Listing reactivated");await load();}catch{toast.error("The moderation action could not be completed");}finally{setBusy(undefined);}}
  return <div className="mx-auto max-w-7xl space-y-7 p-5 sm:p-8"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#EF4217]">Super Admin</p><h1 className="mt-2 text-3xl font-black text-[#141130]">Property listing moderation</h1><p className="mt-2 text-sm text-slate-500">Review public inventory and remove listings that are inaccurate, unsafe or non-compliant.</p></div>{loading?<div className="grid min-h-56 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#EF4217]"/></div>:<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Listing</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Published</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(item=><tr key={item.id}><td className="px-5 py-4"><p className="font-bold text-[#141130]">{item.headline}</p><p className="mt-1 text-xs text-slate-400">Unit #{item.unitId}</p>{item.suspensionReason&&<p className="mt-1 text-xs text-red-600">{item.suspensionReason}</p>}</td><td className="px-5 py-4">{item.listingType}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${item.status==="PUBLISHED"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{item.status==="PUBLISHED"?<BadgeCheck className="h-3.5 w-3.5"/>:<ShieldAlert className="h-3.5 w-3.5"/>}{item.status}</span></td><td className="px-5 py-4 text-slate-500">{item.publishedAt?new Date(item.publishedAt).toLocaleDateString():"—"}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link target="_blank" href={`/property/${item.slug}`} className="rounded-lg border p-2 text-slate-500 hover:text-[#EF4217]" aria-label="Open public listing"><ExternalLink className="h-4 w-4"/></Link><button disabled={busy===item.id} onClick={()=>moderate(item)} className="rounded-lg border border-[#EF4217] px-3 py-2 text-xs font-bold text-[#EF4217] disabled:opacity-50">{busy===item.id?"Working…":item.status==="SUSPENDED"?"Reactivate":"Suspend"}</button></div></td></tr>)}</tbody></table></div>{items.length===0&&<p className="p-10 text-center text-slate-500">No property listings have been published.</p>}</div>}</div>;
}
