"use client";

import {cloneElement,FormEvent,ReactElement,useCallback,useEffect,useId,useMemo,useState} from "react";
import {AlertCircle,Calculator,CheckCircle2,History,Landmark,Link2Off,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Alert,AlertDescription,AlertTitle} from "@/components/ui/alert";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Checkbox} from "@/components/ui/checkbox";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Switch} from "@/components/ui/switch";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Textarea} from "@/components/ui/textarea";
import {disconnectTaxConnection,estimateCgt,estimateMri,myTaxConnections,requestTaxConnection,taxHistory,TaxCalculation,TaxConnection} from "@/services/tax-assist";

const money=(value:number,currency="KES")=>new Intl.NumberFormat("en-KE",{style:"currency",currency,maximumFractionDigits:2}).format(value||0);
const today=new Date().toISOString().slice(0,10);
const month=today.slice(0,7);
const message=(error:unknown)=>error instanceof Error?error.message:"The request could not be completed. Please review the details and try again.";

export default function TaxAssistPage(){
 const [history,setHistory]=useState<TaxCalculation[]>([]);const [connections,setConnections]=useState<TaxConnection[]>([]);const [busy,setBusy]=useState(false);const [result,setResult]=useState<TaxCalculation|null>(null);
 const refresh=useCallback(async()=>{try{const [h,c]=await Promise.all([taxHistory(),myTaxConnections()]);setHistory(h);setConnections(c);}catch(error){toast.error(message(error));}},[]);
 useEffect(()=>{const handle=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(handle);},[refresh]);
 const done=(value:TaxCalculation)=>{setResult(value);setHistory(items=>[value,...items.filter(item=>item.id!==value.id)]);};
 return <div className="mx-auto max-w-6xl space-y-6 p-4 pb-12 md:p-8">
  <div className="rounded-3xl bg-gradient-to-br from-[#0b376d] via-[#1769aa] to-[#16a394] p-6 text-white shadow-xl md:p-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 flex size-11 items-center justify-center rounded-2xl bg-white/15"><Calculator className="size-6"/></div><h1 className="text-3xl font-bold tracking-tight">Slickhood Tax Assist</h1><p className="mt-2 max-w-2xl text-blue-50">Understand an estimated obligation before you file. Calculations stay private in Slickhood unless you deliberately request a KRA connection.</p></div><Badge className="w-fit bg-white/15 text-white hover:bg-white/20">Estimate first · connect only when ready</Badge></div></div>
  <Alert className="border-emerald-200 bg-emerald-50"><ShieldCheck className="size-4 text-emerald-700"/><AlertTitle>No automatic sharing</AlertTitle><AlertDescription>Using either calculator does not send data to eTIMS, iTax or GavaConnect. Estimates are guidance and should be checked before filing.</AlertDescription></Alert>
  <Tabs defaultValue="mri" onValueChange={()=>setResult(null)}><TabsList className="grid h-auto w-full grid-cols-2 md:w-[520px]"><TabsTrigger value="mri" className="py-3">Residential rent (MRI)</TabsTrigger><TabsTrigger value="cgt" className="py-3">Property sale (CGT)</TabsTrigger></TabsList>
   <TabsContent value="mri"><MriForm busy={busy} setBusy={setBusy} onDone={done}/></TabsContent>
   <TabsContent value="cgt"><CgtForm busy={busy} setBusy={setBusy} onDone={done}/></TabsContent>
  </Tabs>
  {result&&<ResultCard value={result}/>} 
  <ConnectionCard values={connections} busy={busy} setBusy={setBusy} refresh={refresh}/>
  <HistoryCard values={history}/>
 </div>;
}

function MriForm({busy,setBusy,onDone}:{busy:boolean;setBusy:(v:boolean)=>void;onDone:(v:TaxCalculation)=>void}){
 const [form,setForm]=useState({period:month,kenyaResidentialProperty:true,residentTaxpayer:true,electedOutOfMri:false,projectedAnnualGrossRent:"",grossRentReceived:"",withholdingCredits:"0"});
 const annual=Number(form.projectedAnnualGrossRent||0),received=Number(form.grossRentReceived||0);const preview=received*.075;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{onDone(await estimateMri({...form,projectedAnnualGrossRent:annual,grossRentReceived:received,withholdingCredits:Number(form.withholdingCredits||0)}));toast.success("MRI estimate saved");}catch(error){toast.error(message(error));}finally{setBusy(false);}};
 return <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>Monthly residential rent</CardTitle><CardDescription>Answer three eligibility questions, then enter what was actually received—not what was merely invoiced.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5">
  <YesNo label="Is this residential property situated in Kenya?" checked={form.kenyaResidentialProperty} onChange={v=>setForm({...form,kenyaResidentialProperty:v})}/>
  <YesNo label="Is the legal taxpayer resident in Kenya?" checked={form.residentTaxpayer} onChange={v=>setForm({...form,residentTaxpayer:v})}/>
  <YesNo label="Has the taxpayer elected out of MRI in writing?" checked={form.electedOutOfMri} onChange={v=>setForm({...form,electedOutOfMri:v})}/>
  <div className="grid gap-4 sm:grid-cols-2"><Field label="Rental month"><Input required type="month" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></Field><Field label="Projected annual gross residential rent"><MoneyInput value={form.projectedAnnualGrossRent} onChange={v=>setForm({...form,projectedAnnualGrossRent:v})}/></Field><Field label="Gross rent actually received this month"><MoneyInput value={form.grossRentReceived} onChange={v=>setForm({...form,grossRentReceived:v})}/></Field><Field label="Verified rental withholding credits"><MoneyInput value={form.withholdingCredits} onChange={v=>setForm({...form,withholdingCredits:v})}/></Field></div>
  <Button disabled={busy} className="w-full bg-[#1769aa]">{busy?"Calculating…":"Calculate and save estimate"}</Button>
 </form></CardContent></Card><Card className="border-blue-100 bg-blue-50/50"><CardHeader><CardTitle className="text-lg">What Slickhood checks</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><Check text="Resident taxpayer and Kenyan residential property"/><Check text="Annual receipts above KES 288,000 and not above KES 15 million"/><Check text="Current effective-dated rate: 7.5% of gross rent received"/><Check text="NIL-return guidance when no rent was received"/><div className="rounded-xl border bg-white p-4"><span className="text-muted-foreground">Quick preview before eligibility checks</span><strong className="mt-1 block text-2xl text-[#0b376d]">{money(preview)}</strong><span className="text-xs text-muted-foreground">The saved result may be zero or route you to another regime.</span></div></CardContent></Card></div>;
}

function CgtForm({busy,setBusy,onDone}:{busy:boolean;setBusy:(v:boolean)=>void;onDone:(v:TaxCalculation)=>void}){
 const [form,setForm]=useState({transferDate:today,transferValue:"",transferCosts:"0",acquisitionCost:"",acquisitionCosts:"0",enhancementCosts:"0",propertyDealer:false,potentialExemption:false,exemptionReason:""});
 const numeric=useMemo(()=>({transferValue:Number(form.transferValue||0),transferCosts:Number(form.transferCosts||0),acquisitionCost:Number(form.acquisitionCost||0),acquisitionCosts:Number(form.acquisitionCosts||0),enhancementCosts:Number(form.enhancementCosts||0)}),[form]);
 const gain=Math.max(0,numeric.transferValue-numeric.transferCosts-numeric.acquisitionCost-numeric.acquisitionCosts-numeric.enhancementCosts);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{onDone(await estimateCgt({...form,...numeric}));toast.success("CGT estimate saved");}catch(error){toast.error(message(error));}finally{setBusy(false);}};
 return <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>Property sale estimate</CardTitle><CardDescription>CGT is different from MRI. Enter documented sale and cost figures; Slickhood will flag cases needing specialist review.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Legal transfer date"><Input required type="date" value={form.transferDate} onChange={e=>setForm({...form,transferDate:e.target.value})}/></Field><Field label="Transfer value / selling price"><MoneyInput value={form.transferValue} onChange={v=>setForm({...form,transferValue:v})}/></Field><Field label="Allowable transfer costs"><MoneyInput value={form.transferCosts} onChange={v=>setForm({...form,transferCosts:v})}/></Field><Field label="Acquisition or construction cost"><MoneyInput value={form.acquisitionCost} onChange={v=>setForm({...form,acquisitionCost:v})}/></Field><Field label="Allowable acquisition costs"><MoneyInput value={form.acquisitionCosts} onChange={v=>setForm({...form,acquisitionCosts:v})}/></Field><Field label="Qualifying enhancement costs"><MoneyInput value={form.enhancementCosts} onChange={v=>setForm({...form,enhancementCosts:v})}/></Field></div><YesNo label="Was the property held as stock of a property-dealing business?" checked={form.propertyDealer} onChange={v=>setForm({...form,propertyDealer:v})}/><YesNo label="Could a statutory exemption apply?" checked={form.potentialExemption} onChange={v=>setForm({...form,potentialExemption:v})}/>{form.potentialExemption&&<Field label="Possible exemption and supporting facts"><Textarea required maxLength={500} value={form.exemptionReason} onChange={e=>setForm({...form,exemptionReason:e.target.value})} placeholder="For example: owner-occupied private residence for the qualifying period"/></Field>}<Button disabled={busy} className="w-full bg-[#1769aa]">{busy?"Calculating…":"Calculate and save estimate"}</Button></form></CardContent></Card><Card className="border-teal-100 bg-teal-50/50"><CardHeader><CardTitle className="text-lg">Calculation preview</CardTitle></CardHeader><CardContent className="space-y-4"><Metric label="Estimated net gain" value={money(gain)}/><Metric label="Indicative CGT at 15%" value={money(gain*.15)}/><p className="text-sm text-muted-foreground">This preview does not apply exemptions or property-dealer treatment. The saved result performs those checks and preserves the rule version used.</p><Alert><AlertCircle className="size-4"/><AlertDescription>Keep sale agreements, title documents, valuations, invoices and proof of every cost entered.</AlertDescription></Alert></CardContent></Card></div>;
}

function ResultCard({value}:{value:TaxCalculation}){const payable=value.estimatedPayable>0;return <Card className={payable?"border-amber-200":"border-emerald-200"}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>Your saved estimate</CardTitle><CardDescription>Calculation #{value.id} · rule {value.rule.ruleCode} version {value.rule.version}</CardDescription></div><Badge variant={payable?"default":"secondary"}>{value.outcome.replaceAll("_"," ")}</Badge></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><Metric label="Taxable amount" value={money(value.taxableAmount,value.currency)}/><Metric label="Estimated tax" value={money(value.estimatedTax,value.currency)}/><Metric label="Estimated payable" value={money(value.estimatedPayable,value.currency)}/></div><p className="mt-5 rounded-xl bg-muted p-4 text-sm">{value.explanation}</p>{value.dueDate&&<p className="mt-3 text-sm"><strong>Guidance date:</strong> {new Date(value.dueDate+"T00:00:00").toLocaleDateString("en-KE",{dateStyle:"long"})}. Confirm the applicable filing deadline before submission.</p>}<a className="mt-3 inline-block text-sm font-semibold text-[#1769aa] underline" href={value.rule.sourceUrl} target="_blank" rel="noreferrer">View the official source used</a></CardContent></Card>}

function ConnectionCard({values,busy,setBusy,refresh}:{values:TaxConnection[];busy:boolean;setBusy:(v:boolean)=>void;refresh:()=>Promise<void>}){const [open,setOpen]=useState(false);const [provider,setProvider]=useState<"ETIMS"|"GAVACONNECT">("GAVACONNECT");const [pin,setPin]=useState("");const [consent,setConsent]=useState(false);const scopes=provider==="ETIMS"?["ISSUE_TAX_INVOICES","QUERY_INVOICE_STATUS"]:["FILE_TAX_RETURN","CREATE_PAYMENT_REFERENCE","QUERY_SUBMISSION_STATUS"];
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await requestTaxConnection({provider,taxpayerPin:pin,requestedScopes:scopes,consentAccepted:consent});toast.success("Connection request recorded. No tax data was transmitted.");setOpen(false);setPin("");setConsent(false);await refresh();}catch(error){toast.error(message(error));}finally{setBusy(false);}};
 const disconnect=async(id:number)=>{setBusy(true);try{await disconnectTaxConnection(id);toast.success("Connection request disconnected");await refresh();}catch(error){toast.error(message(error));}finally{setBusy(false);}};
 return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Landmark className="size-5 text-[#1769aa]"/>Optional KRA connection</CardTitle><CardDescription>eTIMS is for tax invoices. GavaConnect/iTax is for supported filing and payment services.</CardDescription></div><Button variant="outline" onClick={()=>setOpen(v=>!v)}>{open?"Cancel":"Request a connection"}</Button></div></CardHeader><CardContent>{open&&<form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border bg-muted/30 p-4"><Field label="KRA service"><select className="h-10 rounded-md border bg-background px-3" value={provider} onChange={e=>setProvider(e.target.value as typeof provider)}><option value="GAVACONNECT">GavaConnect / iTax services</option><option value="ETIMS">eTIMS tax invoicing</option></select></Field><div><Field label="Taxpayer KRA PIN"><Input required pattern="[A-Za-z][0-9]{9}[A-Za-z]" maxLength={11} autoComplete="off" value={pin} onChange={e=>setPin(e.target.value.toUpperCase())} placeholder="A123456789B"/></Field><span className="mt-2 block text-xs text-muted-foreground">Only a masked PIN is retained at this request stage. Never enter an iTax password.</span></div><div className="rounded-xl border bg-background p-3 text-sm"><strong>Requested access</strong><ul className="mt-2 list-inside list-disc text-muted-foreground">{scopes.map(scope=><li key={scope}>{scope.replaceAll("_"," ").toLowerCase()}</li>)}</ul></div><label className="flex items-start gap-3 text-sm"><Checkbox required checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I deliberately request KRA onboarding for these scopes. I understand this request does not file a return, create an invoice or transmit tax transactions.</span></label><Button disabled={busy||!consent}>Record connection request</Button></form>}<div className="space-y-3">{values.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">No KRA connections requested. Your calculators remain fully available.</p>}{values.map(item=><div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><strong>{item.provider}</strong><Badge variant="outline">{item.status.replaceAll("_"," ")}</Badge></div><p className="mt-1 text-sm text-muted-foreground">PIN {item.taxpayerPinMasked} · {item.environment.toLowerCase()} onboarding</p>{item.reviewNote&&<p className="mt-1 text-sm">{item.reviewNote}</p>}</div><Button variant="ghost" disabled={busy} onClick={()=>void disconnect(item.id)}><Link2Off className="mr-2 size-4"/>Disconnect</Button></div>)}</div></CardContent></Card>}

function HistoryCard({values}:{values:TaxCalculation[]}){return <Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="size-5"/>Calculation history</CardTitle><CardDescription>Saved estimates are immutable and retain the exact rule version used.</CardDescription></CardHeader><CardContent><div className="space-y-3">{values.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">Your completed estimates will appear here.</p>}{values.map(item=><div key={item.id} className="grid gap-2 rounded-xl border p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><strong>{item.calculationType} · {item.taxPeriod}</strong><p className="text-sm text-muted-foreground">{item.outcome.replaceAll("_"," ")} · rule v{item.rule.version} · {new Date(item.createdOn).toLocaleString("en-KE")}</p></div><div className="text-left sm:text-right"><span className="text-xs text-muted-foreground">Estimated payable</span><strong className="block text-lg">{money(item.estimatedPayable,item.currency)}</strong></div></div>)}</div></CardContent></Card>}

function Field({label,children}:{label:string;children:ReactElement<{id?:string}>}){const id=useId();return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label>{cloneElement(children,{id})}</div>}
function MoneyInput({id,value,onChange}:{id?:string;value:string;onChange:(v:string)=>void}){return <div className="relative"><span className="absolute left-3 top-2.5 text-sm text-muted-foreground">KES</span><Input id={id} required type="number" min="0" step="0.01" className="pl-12" value={value} onChange={e=>onChange(e.target.value)}/></div>}
function YesNo({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between gap-4 rounded-xl border p-4"><Label className="leading-5">{label}</Label><div className="flex items-center gap-2 text-sm"><span>{checked?"Yes":"No"}</span><Switch checked={checked} onCheckedChange={onChange}/></div></div>}
function Check({text}:{text:string}){return <div className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600"/><span>{text}</span></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-background p-4"><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-xl text-[#0b376d]">{value}</strong></div>}
