"use client";

import {useEffect,useMemo,useState} from "react";
import {BriefcaseBusiness,CalendarDays,MapPin,Navigation,Search,ShieldCheck,ShoppingBasket,Star,X} from "lucide-react";
import {useAuthStore} from "@/store/authStore";
import {cancelServiceBooking,completeServiceBooking,confirmServiceBooking,createServiceBooking,getMyServiceBookings,getServiceCategories,initiateServiceBookingPayment,MarketplaceService,rateMarketplaceService,searchMarketplace,ServiceBooking,startServiceBooking} from "@/services/serviceProvider";
import SokoMarketplace from "./soko-marketplace";

type Category={id:number;name:string};
type BookingDialog={kind:"pay"|"complete"|"cancel"|"rate";booking:ServiceBooking}|null;
const apiDate=(value:string)=>{const [d,t]=value.split("T");return `${d} ${t.length===5?`${t}:00`:t}`};
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-KE",{style:"currency",currency}).format(amount);
const distance=(a:{latitude:number;longitude:number}|null,b:{latitude?:number;longitude?:number})=>{if(!a||b.latitude==null||b.longitude==null)return null;const r=6371,dLat=(b.latitude-a.latitude)*Math.PI/180,dLng=(b.longitude-a.longitude)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.latitude*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(dLng/2)**2;return Math.round(r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))*10)/10;};

export default function Marketplace(){const [catalog,setCatalog]=useState<"services"|"soko">("services");return <div className="space-y-5 px-3 py-6"><section className="rounded-2xl border bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#FF4B1F]">Create and explore your market</p><h1 className="mt-1 text-2xl font-bold text-[#14235C]">Choose what you want to browse</h1><div className="mt-4 grid gap-3 md:grid-cols-2"><button onClick={()=>setCatalog("services")} className={`flex items-center gap-4 rounded-2xl border p-5 text-left ${catalog==="services"?"border-[#FF4B1F] bg-orange-50":""}`}><BriefcaseBusiness className="h-8 w-8 text-[#FF4B1F]"/><span><b className="block text-[#14235C]">Service Catalog</b><small className="text-gray-500">Repairs, cleaning, professional and home services</small></span></button><button onClick={()=>setCatalog("soko")} className={`flex items-center gap-4 rounded-2xl border p-5 text-left ${catalog==="soko"?"border-[#FF4B1F] bg-orange-50":""}`}><ShoppingBasket className="h-8 w-8 text-[#FF4B1F]"/><span><b className="block text-[#14235C]">Soko · Groceries Catalog</b><small className="text-gray-500">Fresh produce, food, beverages and household products</small></span></button></div></section>{catalog==="services"?<ServiceMarketplace/>:<SokoMarketplace/>}</div>}

function ServiceMarketplace(){
 const {token,permissions}=useAuthStore(); const [tab,setTab]=useState<"browse"|"bookings">("browse");
 const [services,setServices]=useState<MarketplaceService[]>([]),[bookings,setBookings]=useState<ServiceBooking[]>([]),[categories,setCategories]=useState<Category[]>([]);
 const [query,setQuery]=useState(""),[categoryId,setCategoryId]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [coords,setCoords]=useState<{latitude:number;longitude:number}|null>(null),[radius,setRadius]=useState(25),[locationState,setLocationState]=useState("Location off");
 const [selected,setSelected]=useState<MarketplaceService|null>(null),[when,setWhen]=useState(""),[notes,setNotes]=useState("");
 const [dialog,setDialog]=useState<BookingDialog>(null),[dialogValue,setDialogValue]=useState(""),[rating,setRating]=useState(5),[actionBusy,setActionBusy]=useState(false);
 const canConfirm=permissions.includes("confirm_sp_booking"),canComplete=permissions.includes("complete_sp_booking");

 const loadServices=async()=>{setLoading(true);setError("");try{const r=await searchMarketplace({query:query.trim()||undefined,categoryId:categoryId||undefined,radiusKm:radius,...(coords??{})});setServices(r.data?.data??[]);}catch{setError("The marketplace could not be loaded.");}finally{setLoading(false);}};
 const loadBookings=async()=>{if(!token)return;try{const r=await getMyServiceBookings(token);setBookings(r.data?.data??[]);}catch{setError("Bookings could not be loaded.");}};
 useEffect(()=>{if(token)getServiceCategories(token,{size:100}).then(r=>setCategories(r.data?.data??[])).catch(()=>{});},[token]);
 useEffect(()=>{const id=setTimeout(loadServices,300);return()=>clearTimeout(id);},[query,categoryId,coords,radius]);
 const locate=()=>{if(!navigator.geolocation)return setLocationState("Location unavailable");setLocationState("Locating...");navigator.geolocation.getCurrentPosition(p=>{setCoords({latitude:p.coords.latitude,longitude:p.coords.longitude});setLocationState(`Nearby within ${radius} km`);},()=>setLocationState("Permission declined — showing all providers"),{enableHighAccuracy:true,timeout:10000});};
 useEffect(()=>{if(tab==="bookings")loadBookings();},[tab,token]);
 const trusted=useMemo(()=>services.filter(s=>s.riskLabel==="TRUSTED"||s.riskLabel==="VERIFIED").length,[services]);
 const book=async()=>{if(!token||!selected||!when)return setError("Choose a future service date and time.");try{await createServiceBooking(token,{serviceId:selected.id,scheduledAt:apiDate(when),notes});setSelected(null);setWhen("");setNotes("");setTab("bookings");await loadBookings();}catch(e:any){setError(e?.response?.data?.description??"The booking could not be created.");}};
 const act=async(id:number,action:"confirm"|"start")=>{if(!token)return;try{setActionBusy(true);if(action==="confirm")await confirmServiceBooking(token,id);else await startServiceBooking(token,id);await loadBookings();}catch(e:any){setError(e?.response?.data?.description??"The booking could not be updated.");}finally{setActionBusy(false);}};
 const openDialog=(kind:NonNullable<BookingDialog>["kind"],booking:ServiceBooking)=>{setDialog({kind,booking});setDialogValue("");setRating(5);setError("");};
 const submitDialog=async()=>{if(!token||!dialog)return;const b=dialog.booking;try{setActionBusy(true);if(dialog.kind==="pay"){if(!b.invoiceRef||!b.paymentAccountId||!b.paymentChannel)throw new Error("This booking is not ready for payment.");const response=await initiateServiceBookingPayment(b.invoiceRef,b.paymentAccountId,b.paymentChannel,dialogValue.trim()||undefined);const destination=response.data?.data?.[0];if(typeof destination==="string"&&destination.startsWith("http")){window.location.assign(destination);return;}}else if(dialog.kind==="complete"){if(!dialogValue.trim())return setError("Add the signed job card, photo, or completion evidence reference.");await completeServiceBooking(token,b.id,dialogValue.trim());}else if(dialog.kind==="cancel"){if(!dialogValue.trim())return setError("Tell the other party why this booking is being cancelled.");await cancelServiceBooking(token,b.id,dialogValue.trim());}else await rateMarketplaceService(token,{bookingId:b.id,serviceId:b.serviceId,stars:rating,comment:dialogValue.trim()||undefined});setDialog(null);await loadBookings();}catch(e:any){setError(e?.response?.data?.description??e?.message??"The booking could not be updated.");}finally{setActionBusy(false);}};

 return <div className="space-y-6">
  <header className="rounded-3xl bg-[#020B2D] p-7 text-white"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-orange-300">Slickhood Marketplace</p><h1 className="mt-2 text-3xl font-bold">Trusted help for every property</h1><p className="mt-2 max-w-2xl text-sm text-white/70">Discover reviewed providers, request a convenient time, follow fulfilment, and rate completed work.</p></div><div className="flex gap-4 text-center"><div><p className="text-2xl font-bold">{services.length}</p><p className="text-xs text-white/60">available</p></div><div><p className="text-2xl font-bold">{trusted}</p><p className="text-xs text-white/60">verified</p></div></div></div></header>
  <div className="flex gap-2"><button onClick={()=>setTab("browse")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab==="browse"?"bg-[#FF4B1F] text-white":"bg-white text-[#020B2D]"}`}>Browse services</button><button onClick={()=>setTab("bookings")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab==="bookings"?"bg-[#FF4B1F] text-white":"bg-white text-[#020B2D]"}`}>My bookings</button></div>
  {error&&<p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {tab==="browse"?<>
   <div className="grid gap-3 rounded-2xl border bg-white p-4 lg:grid-cols-[1fr_220px_150px_auto]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a service or provider" className="w-full rounded-xl border py-2.5 pl-10 pr-3 text-sm"/></label><select value={categoryId} onChange={e=>setCategoryId(Number(e.target.value))} className="rounded-xl border px-3 text-sm"><option value={0}>All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={radius} onChange={e=>setRadius(Number(e.target.value))} className="rounded-xl border px-3 text-sm"><option value={5}>5 km</option><option value={10}>10 km</option><option value={25}>25 km</option><option value={50}>50 km</option></select><button onClick={locate} className="inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><Navigation className="h-4 w-4"/>{locationState}</button></div>
   {loading?<p className="py-16 text-center text-gray-500">Finding providers...</p>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map(s=>{const km=distance(coords,s);return <article key={s.id} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#FF4B1F]"><BriefcaseBusiness/></div>{s.riskLabel&&<span className="inline-flex h-fit items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700"><ShieldCheck className="h-3 w-3"/>{s.riskLabel.replace("_"," ")}</span>}</div><h2 className="mt-4 text-lg font-bold text-[#020B2D]">{s.categoryName}</h2><p className="mt-1 text-sm text-gray-500">{s.serviceProviderName}</p>{s.latitude&&<p className="mt-2 flex items-center gap-1 text-xs text-gray-400"><MapPin className="h-3 w-3"/>{km!=null?`${km} km away`:"Location verified"}</p>}<div className="mt-5 flex items-end justify-between"><div><p className="text-lg font-bold text-[#020B2D]">{money(s.amount,s.currency)}</p><p className="text-xs text-gray-400">per {s.pricingUnit.toLowerCase().replaceAll("_"," ")}</p></div><button onClick={()=>setSelected(s)} className="rounded-xl bg-[#FF4B1F] px-4 py-2 text-sm font-semibold text-white">Book service</button></div></article>})}{!services.length&&<p className="col-span-full py-16 text-center text-gray-500">No listed services match your search.</p>}</div>}
  </>:<section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold text-[#020B2D]">Service jobs</h2></div><div className="divide-y">{bookings.map(b=><div key={b.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{b.serviceName}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold">{b.status.replaceAll("_"," ")}</span></div><p className="mt-1 text-sm text-gray-500">{b.serviceProviderName} · {new Date(b.scheduledAt).toLocaleString("en-KE")}</p><p className="text-xs text-gray-400">Booked by {b.bookedByUserName}{b.invoiceRef?` · Invoice ${b.invoiceRef}`:""}{b.paymentStatus?` · ${b.paymentStatus}`:""}</p>{b.refundStatus&&b.refundStatus!=="NOT_REQUIRED"&&<p className="mt-1 text-xs font-medium text-amber-700">Refund: {b.refundStatus.replaceAll("_"," ")}</p>}</div><div className="flex flex-wrap gap-2">{b.status==="PENDING"&&canConfirm&&<button disabled={actionBusy} onClick={()=>act(b.id,"confirm")} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">Accept & invoice</button>}{b.status==="AWAITING_PAYMENT"&&!canConfirm&&<button onClick={()=>openDialog("pay",b)} className="rounded-lg bg-orange-50 px-3 py-2 text-xs font-semibold text-orange-700">Pay now</button>}{b.status==="PAID"&&canComplete&&<button disabled={actionBusy} onClick={()=>act(b.id,"start")} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">Start work</button>}{b.status==="IN_PROGRESS"&&canComplete&&<button onClick={()=>openDialog("complete",b)} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Complete with evidence</button>}{!["COMPLETED","CANCELLED"].includes(b.status)&&<button onClick={()=>openDialog("cancel",b)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Cancel</button>}{b.status==="COMPLETED"&&!canComplete&&<button onClick={()=>openDialog("rate",b)} className="inline-flex items-center gap-1 rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700"><Star className="h-3 w-3"/>Rate</button>}</div></div>)}{!bookings.length&&<p className="py-16 text-center text-gray-500">No service bookings yet.</p>}</div></section>}
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Book {selected.categoryName}</h2><p className="text-sm text-gray-500">{selected.serviceProviderName} · {money(selected.amount,selected.currency)}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="mt-5 space-y-4"><label className="block text-sm font-medium">Preferred date and time<input type="datetime-local" value={when} min={new Date(Date.now()+3600000).toISOString().slice(0,16)} onChange={e=>setWhen(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm font-medium">Job details<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe the issue, access instructions, and any urgency" className="mt-1 min-h-28 w-full rounded-xl border p-3"/></label><button onClick={book} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#FF4B1F] p-3 font-semibold text-white"><CalendarDays className="h-4 w-4"/>Send booking request</button></div></div></div>}
  {dialog&&<div role="dialog" aria-modal="true" aria-labelledby="booking-action-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="booking-action-title" className="text-xl font-bold">{dialog.kind==="pay"?"Continue to payment":dialog.kind==="complete"?"Complete this job":dialog.kind==="cancel"?"Cancel this booking":"Rate this service"}</h2><p className="mt-1 text-sm text-gray-500">{dialog.booking.serviceName} · {dialog.booking.serviceProviderName}</p></div><button aria-label="Close" onClick={()=>setDialog(null)}><X/></button></div><div className="mt-5 space-y-4">{dialog.kind==="rate"&&<label className="block text-sm font-medium">Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))} className="mt-1 w-full rounded-xl border p-3">{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} star{value===1?"":"s"}</option>)}</select></label>}<label className="block text-sm font-medium">{dialog.kind==="pay"?"Payment phone (optional)":dialog.kind==="complete"?"Evidence reference":dialog.kind==="cancel"?"Cancellation reason":"Comment (optional)"}{dialog.kind==="rate"?<textarea value={dialogValue} onChange={e=>setDialogValue(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3"/>:<input autoFocus value={dialogValue} onChange={e=>setDialogValue(e.target.value)} placeholder={dialog.kind==="complete"?"Signed job card, photo, or document reference":undefined} className="mt-1 w-full rounded-xl border p-3"/>}</label><button disabled={actionBusy} onClick={submitDialog} className="w-full rounded-xl bg-[#FF4B1F] p-3 font-semibold text-white disabled:opacity-50">{actionBusy?"Please wait…":"Continue"}</button></div></div></div>}
 </div>;
}
