"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
import { toast } from "sonner";
import { salesService } from "@/services/business-workflows.service";
import { SaleStatus,SaleTransaction } from "@/types/business-workflows";
import { useAuthStore } from "@/store/authStore";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { apiErrorMessage } from "@/lib/api-error";
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Badge } from "@/components/ui/badge";

const next:Partial<Record<SaleStatus,SaleStatus[]>>={LEAD:["VIEWING","OFFERED","CANCELLED"],VIEWING:["OFFERED","CANCELLED"],OFFERED:["RESERVED","CANCELLED"],RESERVED:["DUE_DILIGENCE","CANCELLED"],DUE_DILIGENCE:["AGREEMENT","CANCELLED"],AGREEMENT:["COMPLETION","CANCELLED"],COMPLETION:["COMPLETED","CANCELLED"]};
const label=(s:string)=>s.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function SalesPage(){
 const permissions=useAuthStore(s=>s.permissions),canManage=permissions.includes("manage_sale_pipeline"),canAccept=permissions.includes("accept_sale_offer");
 const [items,setItems]=useState<SaleTransaction[]>([]),[busy,setBusy]=useState(false);const [propertyId,setPropertyId]=useState(""),[unitId,setUnitId]=useState(""),[buyerUserId,setBuyerUserId]=useState(""),[askingPrice,setAskingPrice]=useState(""),[currency,setCurrency]=useState("KES");
 const load=useCallback(async()=>{try{const r=await salesService.list();setItems(r.data?.data??[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Could not load sales."))}},[]);useEffect(()=>{load()},[load]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);try{await salesService.create({propertyId:Number(propertyId),unitId:unitId?Number(unitId):undefined,buyerUserId:Number(buyerUserId),askingPrice:Number(askingPrice),currency});toast.success("Sale workflow created.");await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not create sale."))}finally{setBusy(false)}}
 async function advance(item:SaleTransaction,status:SaleStatus){setBusy(true);try{await salesService.update(item.id,{status});toast.success(`Sale moved to ${label(status)}.`);await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not update sale."))}finally{setBusy(false)}}
 async function accept(id:number){try{await salesService.acceptOffer(id);toast.success("Offer accepted.");await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not accept offer."))}}
 return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#EF4217]">SlickHood Property Sales</p><h1 className="mt-1 text-3xl font-bold">Property Sale Management</h1><p className="text-muted-foreground">Manage the complete buyer journey: interest, viewings, offers, due diligence, agreements, completion and ownership handover.</p></div>
 {canManage&&<Card><CardHeader><CardTitle>Start sale workflow</CardTitle><CardDescription>The buyer receives a separate role view and controls offer acceptance.</CardDescription></CardHeader><CardContent><form onSubmit={create} className="grid gap-4 md:grid-cols-5"><div><Label>Property ID</Label><Input required type="number" min="1" value={propertyId} onChange={e=>setPropertyId(e.target.value)}/></div><div><Label>Unit ID</Label><Input type="number" min="1" value={unitId} onChange={e=>setUnitId(e.target.value)}/></div><div><Label>Buyer user ID</Label><Input required type="number" min="1" value={buyerUserId} onChange={e=>setBuyerUserId(e.target.value)}/></div><div><Label>Asking price</Label><Input required type="number" min="0.01" step="0.01" value={askingPrice} onChange={e=>setAskingPrice(e.target.value)}/></div><div><Label>Currency</Label><Input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></div><div className="md:col-span-5"><Button disabled={busy} className="bg-[#EF4217]">Start sale</Button></div></form></CardContent></Card>}
 <Card><CardHeader><CardTitle>Property sale transactions</CardTitle><CardDescription>Every transaction retains its buyer, property, price and stage history.</CardDescription></CardHeader><CardContent className="space-y-3">{items.length===0&&<p className="py-8 text-center text-muted-foreground">No property sale transactions for this active role.</p>}{items.map(item=><div key={item.id} className="rounded-lg border p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><div className="flex gap-2"><strong>Sale #{item.id}</strong><Badge>{label(item.status)}</Badge></div><p className="text-sm text-muted-foreground">Property {item.propertyId}{item.unitId?` · Unit ${item.unitId}`:""} · Buyer #{item.buyerUserId} · {item.currency} {item.askingPrice.toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{canAccept&&item.status==="OFFERED"&&<Button size="sm" onClick={()=>accept(item.id)}>Accept offer</Button>}{canManage&&(next[item.status]??[]).map(status=><Button key={status} size="sm" variant={status==="CANCELLED"?"destructive":"outline"} disabled={busy} onClick={()=>advance(item,status)}>{label(status)}</Button>)}</div></div></div>)}</CardContent></Card></div>
}
