import {API} from "@/lib/api";

export type AssetPayload={propertyId?:number;assetType:string;name:string;reference?:string;location?:string;currency:string;acquisitionCost:number;acquisitionDate?:string;currentValue:number;valuationDate:string;status:string;exchangeCode?:string;instrumentSymbol?:string;quantity?:number;averageUnitCost?:number;pricingMode?:"MANUAL"|"MARKET"};
export type WealthPropertyOption={id:number;name:string;description?:string};
export type WealthAssetType={id:number;code:string;label:string;description?:string;displayOrder:number;marketPricingAllowed:boolean;active:boolean};
export const defaultWealthAssetTypes: WealthAssetType[] = [
 {id:-1,code:"PROPERTY",label:"Property",description:"Residential or commercial property",displayOrder:10,marketPricingAllowed:false,active:true},
 {id:-2,code:"LAND",label:"Land",description:"Vacant, agricultural or development land",displayOrder:20,marketPricingAllowed:false,active:true},
 {id:-3,code:"LISTED_SECURITY",label:"Shares",description:"Exchange-listed shares and securities",displayOrder:30,marketPricingAllowed:true,active:true},
 {id:-4,code:"FUND",label:"Funds",description:"Unit trusts, mutual funds and exchange-traded funds",displayOrder:40,marketPricingAllowed:true,active:true},
 {id:-5,code:"GOVERNMENT_SECURITY",label:"Government securities",description:"Treasury bills and bonds",displayOrder:50,marketPricingAllowed:true,active:true},
 {id:-6,code:"INVESTMENT",label:"Other investments",description:"Private or managed investments",displayOrder:60,marketPricingAllowed:false,active:true},
 {id:-7,code:"SACCO",label:"SACCO",description:"Deposits and shares held in a SACCO",displayOrder:70,marketPricingAllowed:false,active:true},
 {id:-8,code:"PENSION",label:"Pension",description:"Retirement and pension accounts",displayOrder:80,marketPricingAllowed:false,active:true},
 {id:-9,code:"CASH",label:"Cash and bank balances",description:"Cash and bank balances",displayOrder:90,marketPricingAllowed:false,active:true},
 {id:-10,code:"BUSINESS",label:"Business",description:"Ownership interests in a business",displayOrder:100,marketPricingAllowed:false,active:true},
 {id:-11,code:"VEHICLE",label:"Vehicle",description:"Cars and other vehicles",displayOrder:110,marketPricingAllowed:false,active:true},
 {id:-12,code:"DIGITAL_ASSET",label:"Digital assets",description:"Digital assets tracked manually or by market price",displayOrder:120,marketPricingAllowed:true,active:true},
 {id:-13,code:"OTHER",label:"Other",description:"Other asset types",displayOrder:999,marketPricingAllowed:false,active:true},
];
export const wealthService={
 dashboard:(years=5,valueGrowth=5,incomeGrowth=3,expenseGrowth=3)=>API.get("/wealth/dashboard",{params:{years,valueGrowth,incomeGrowth,expenseGrowth}}),
 assets:()=>API.get("/wealth/assets"),
 assetTypes:()=>API.get("/wealth/asset-types"),
 adminSummary:()=>API.get("/wealth/admin/summary"),
 adminAssetTypes:()=>API.get("/wealth/admin/asset-types"),
 createAssetType:(data:Partial<WealthAssetType>)=>API.post("/wealth/admin/asset-types",data),
 updateAssetType:(id:number,data:Partial<WealthAssetType>)=>API.put(`/wealth/admin/asset-types/${id}`,data),
 propertyOptions:()=>API.get("/wealth/property-options"),
 createAsset:(data:AssetPayload)=>API.post("/wealth/assets",data),
 updateAsset:(id:number,data:AssetPayload)=>API.put(`/wealth/assets/${id}`,data),
 archiveAsset:(id:number)=>API.delete(`/wealth/assets/${id}`),
 refreshMarket:(id:number)=>API.post(`/wealth/assets/${id}/market/refresh`),
 addValuation:(id:number,data:{amount:number;valuationDate:string;source:string;notes?:string})=>API.post(`/wealth/assets/${id}/valuations`,data),
 addCashFlow:(id:number,data:{flowType:"INCOME"|"EXPENSE";category:string;amount:number;entryDate:string;description?:string;recurring:boolean})=>API.post(`/wealth/assets/${id}/cash-flows`,data),
 updateCashFlow:(id:number,data:{flowType:"INCOME"|"EXPENSE";category:string;amount:number;entryDate:string;description?:string;recurring:boolean})=>API.put(`/wealth/cash-flows/${id}`,data),
 archiveCashFlow:(id:number)=>API.delete(`/wealth/cash-flows/${id}`),
 addLiability:(id:number,data:{lender:string;currency:string;originalPrincipal:number;outstandingPrincipal:number;annualInterestRate?:number;monthlyPayment?:number;startDate?:string;maturityDate?:string})=>API.post(`/wealth/assets/${id}/liabilities`,data),
 updateLiabilityBalance:(id:number,data:{outstandingPrincipal:number;monthlyPayment?:number;maturityDate?:string})=>API.put(`/wealth/liabilities/${id}/balance`,data),
 archiveLiability:(id:number)=>API.delete(`/wealth/liabilities/${id}`),
 addObligation:(id:number,data:{obligationType:string;title:string;effectiveDate?:string;dueDate?:string;expiryDate?:string;amount?:number;currency?:string;reminderDays:number;notes?:string})=>API.post(`/wealth/assets/${id}/obligations`,data),
 completeObligation:(id:number)=>API.post(`/wealth/obligations/${id}/complete`),
 reopenObligation:(id:number)=>API.post(`/wealth/obligations/${id}/reopen`),
 archiveObligation:(id:number)=>API.delete(`/wealth/obligations/${id}`),
 addGoal:(data:{goalType:string;name:string;targetAmount:number;currency:string;targetDate:string})=>API.post("/wealth/goals",data),
 goal:(id:number)=>API.get(`/wealth/goals/${id}`),
 updateGoal:(id:number,data:{goalType:string;name:string;targetAmount:number;currency:string;targetDate:string})=>API.put(`/wealth/goals/${id}`,data),
 archiveGoal:(id:number)=>API.delete(`/wealth/goals/${id}`),
 uploadDocument:(id:number,data:FormData)=>API.post(`/wealth/assets/${id}/vault`,data),
 documents:(id:number)=>API.get(`/wealth/assets/${id}/vault`),
 ledger:(id:number)=>API.get(`/wealth/assets/${id}/ledger`),
 vault:()=>API.get("/wealth/vault"),
 document:(id:number)=>API.get(`/wealth/vault/${id}`),
 uploadVaultDocument:(data:FormData)=>API.post("/wealth/vault",data),
 archiveDocument:(id:number)=>API.delete(`/wealth/vault/${id}`),
};
