"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, PackageCheck, RefreshCw, Truck } from "lucide-react";
import { toast } from "sonner";
import { acceptSokoAssignment, collectSokoDelivery, confirmSokoDelivery, failSokoDelivery, myRiderAssignments, returnSokoDelivery, SokoOrderDetail, uploadSokoDeliveryProof } from "@/services/soko";

const error=(e:unknown,fallback:string)=>(e as {response?:{data?:{description?:string}}}).response?.data?.description??fallback;
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

export default function RiderDeliveriesPage(){
 const [orders,setOrders]=useState<SokoOrderDetail[]>([]),[busy,setBusy]=useState<number>(),[code,setCode]=useState<Record<number,string>>({}),[proof,setProof]=useState<Record<number,File|undefined>>({});
 const load=useCallback(async()=>{try{const r=await myRiderAssignments();setOrders(r.data?.data??[]);}catch(e){toast.error(error(e,"Rider assignments could not be loaded."));}},[]);
 useEffect(()=>{void load();},[load]);
 const run=async(id:number,action:()=>Promise<unknown>,success:string)=>{setBusy(id);try{await action();toast.success(success);await load();}catch(e){toast.error(error(e,"The delivery could not be updated."));}finally{setBusy(undefined);}};
 const exception=async(x:SokoOrderDetail,kind:"fail"|"return")=>{const reason=prompt(kind==="fail"?"Why could the delivery not be completed?":"Record the return reason:");if(!reason?.trim())return;await run(x.order.id,()=>kind==="fail"?failSokoDelivery(x.order.id,reason.trim()):returnSokoDelivery(x.order.id,reason.trim()),kind==="fail"?"Failed attempt recorded. The buyer was notified.":"Return recorded and refund review requested.");};
 const complete=async(x:SokoOrderDetail)=>{const file=proof[x.order.id],deliveryCode=code[x.order.id]??"";if(!file||!/^[0-9]{6}$/.test(deliveryCode))return toast.error("Add a proof photo and enter the buyer's six-digit code.");await run(x.order.id,async()=>{await uploadSokoDeliveryProof(x.order.id,file);await confirmSokoDelivery(x.order.id,deliveryCode);},"Delivery completed and verified.");};
 return <div className="space-y-5 px-3 py-6"><header className="rounded-3xl bg-[#07143D] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-300">Soko delivery</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">My deliveries</h1><p className="mt-2 text-white/70">Accept an assignment, confirm collection, track exceptions and complete delivery only with the buyer's code.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 font-semibold text-[#07143D]"><RefreshCw className="h-4 w-4"/>Refresh</button></div></header>
  <section className="space-y-4">{orders.map(x=><article key={x.order.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-[#FF4B1F]"/><b>{x.order.orderNumber}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{label(x.order.status)}</span></div><p className="mt-2 text-sm text-gray-600">{x.storeName} · {x.items.map(i=>`${i.productName} × ${i.quantity}`).join(", ")}</p><p className="mt-1 text-sm">Deliver to: {x.order.deliveryAddress||"Address unavailable"}</p>{x.order.expectedArrivalAt&&<p className="text-xs text-gray-500">Expected by {new Date(x.order.expectedArrivalAt).toLocaleString()}</p>}{x.order.deliveryExceptionReason&&<p className="mt-2 text-sm text-red-700">{x.order.deliveryExceptionReason}</p>}</div><div className="flex flex-wrap items-start gap-2">{x.order.status==="DELIVERY_ASSIGNED"&&<button disabled={busy===x.order.id} onClick={()=>run(x.order.id,()=>acceptSokoAssignment(x.order.id),"Assignment accepted.")} className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Accept</button>}{x.order.status==="ASSIGNMENT_ACCEPTED"&&<button disabled={busy===x.order.id} onClick={()=>run(x.order.id,()=>collectSokoDelivery(x.order.id),"Collection confirmed. The code was sent only to the buyer.")} className="rounded-xl bg-amber-600 px-4 py-2 font-semibold text-white"><PackageCheck className="mr-2 inline h-4 w-4"/>Collected</button>}{["DELIVERY_ASSIGNED","ASSIGNMENT_ACCEPTED","DISPATCHED"].includes(x.order.status)&&<button onClick={()=>exception(x,"fail")} className="rounded-xl border border-red-200 px-4 py-2 text-red-700">Record failed attempt</button>}{x.order.status==="DELIVERY_FAILED"&&<button onClick={()=>exception(x,"return")} className="rounded-xl border px-4 py-2">Record return</button>}</div></div>{x.order.status==="DISPATCHED"&&<div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-[1fr_220px_auto]"><label className="text-sm font-semibold">Proof of delivery photo<input type="file" accept="image/jpeg,image/png" onChange={e=>setProof({...proof,[x.order.id]:e.target.files?.[0]})} className="mt-1 block w-full rounded-lg border bg-white p-2 font-normal"/></label><label className="text-sm font-semibold">Buyer's six-digit code<input inputMode="numeric" maxLength={6} value={code[x.order.id]??""} onChange={e=>setCode({...code,[x.order.id]:e.target.value.replace(/\D/g,"").slice(0,6)})} className="mt-1 block w-full rounded-lg border p-2 font-mono text-lg tracking-[.2em]"/></label><button disabled={busy===x.order.id} onClick={()=>complete(x)} className="self-end rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white"><CheckCircle2 className="mr-2 inline h-4 w-4"/>Complete</button></div>}</article>)}{!orders.length&&<div className="rounded-2xl border bg-white py-16 text-center text-gray-500">No rider assignments are linked to this SlickHood account.</div>}</section>
 </div>;
}
