"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Landmark,RefreshCw,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {wealthService,WealthAssetType} from "@/services/wealth.service";
import {apiErrorMessage} from "@/lib/api-error";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Badge} from "@/components/ui/badge";
type Summary={activeAssets:number;owners:number;vaultDocuments:number;marketPricedAssets:number;activeAssetTypes:number};
const blank={code:"",label:"",description:"",displayOrder:100,marketPricingAllowed:false,active:true};
export default function WealthManagement(){
 const [summary,setSummary]=useState<Summary|null>(null),[types,setTypes]=useState<WealthAssetType[]>([]),[form,setForm]=useState(blank),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const [s,t]=await Promise.all([wealthService.adminSummary(),wealthService.adminAssetTypes()]);setSummary(s.data?.data??null);setTypes(Array.isArray(t.data?.data)?t.data.data:[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Wealth administration could not be loaded."))}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);try{await wealthService.createAssetType(form);setForm(blank);toast.success("Asset type added.");await load()}catch(error:unknown){toast.error(apiErrorMessage(error,"Asset type could not be added."))}finally{setBusy(false)}}
 async function toggle(type:WealthAssetType){setBusy(true);try{await wealthService.updateAssetType(type.id,{code:type.code,label:type.label,description:type.description,displayOrder:type.displayOrder,marketPricingAllowed:type.marketPricingAllowed,active:!type.active});toast.success(type.active?"Asset type hidden from new entries.":"Asset type restored.");await load()}catch(error:unknown){toast.error(apiErrorMessage(error,"Asset type could not be updated."))}finally{setBusy(false)}}
 return <div className="space-y-6 px-3 py-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#FF4B1F]">Private wealth controls</p><h1 className="mt-1 text-3xl font-bold text-[#162B63]">Wealth administration</h1><p className="text-slate-500">Manage the asset catalogue and platform health without exposing anyone&apos;s portfolio or vault documents.</p></div><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw className={`mr-2 size-4 ${busy?"animate-spin":""}`}/>Refresh</Button></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Active assets",summary?.activeAssets],["Wealth users",summary?.owners],["Vault documents",summary?.vaultDocuments],["Market priced",summary?.marketPricedAssets],["Active types",summary?.activeAssetTypes]].map(([label,value])=><Card key={String(label)}><CardContent className="pt-5"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-[#162B63]">{Number(value??0).toLocaleString()}</p></CardContent></Card>)}</div>
 <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="size-5 text-[#FF4B1F]"/>Add asset type</CardTitle><CardDescription>Codes become stable reporting keys and cannot be renamed later.</CardDescription></CardHeader><CardContent><form onSubmit={create} className="space-y-4"><Field label="Code"><Input required pattern="[A-Z][A-Z0-9_]{1,39}" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"")})}/></Field><Field label="Customer label"><Input required maxLength={100} value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></Field><Field label="Description"><Input maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Display order"><Input type="number" min={0} value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:Number(e.target.value)})}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.marketPricingAllowed} onChange={e=>setForm({...form,marketPricingAllowed:e.target.checked})}/>Allow live market pricing</label><Button disabled={busy} className="w-full">Add asset type</Button></form></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-600"/>Asset type catalogue</CardTitle><CardDescription>Deactivation only affects new records; it never deletes or changes existing customer wealth data.</CardDescription></CardHeader><CardContent className="space-y-3">{types.map(type=><div key={type.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{type.label}</b><Badge variant="outline">{type.code}</Badge><Badge variant={type.active?"secondary":"outline"}>{type.active?"ACTIVE":"HIDDEN"}</Badge>{type.marketPricingAllowed&&<Badge className="bg-blue-600">MARKET</Badge>}</div><p className="mt-1 text-sm text-slate-500">{type.description||"No description"} · order {type.displayOrder}</p></div><Button variant="outline" disabled={busy} onClick={()=>void toggle(type)}>{type.active?"Hide":"Restore"}</Button></div>)}</CardContent></Card></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
