"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Clock,FileCheck2,RefreshCw,ShieldCheck,Users} from "lucide-react";
import {insuranceService,InsuranceCase,InsuranceClaim,InsuranceCompany,InsuranceOperationsSummary,InsurancePolicy} from "@/services/insurance.service";
import {useAuthStore} from "@/store/authStore";import {apiErrorMessage} from "@/lib/api-error";import {toast} from "sonner";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Badge} from "@/components/ui/badge";import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Textarea} from "@/components/ui/textarea";import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
const title=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase());
const blank={companyId:"",quoteNumber:"",currency:"KES",basePremium:"",taxesLevies:"0",totalPremium:"",excessDetails:"",coverageSummary:"",exclusions:"",validUntil:""};
export default function InsuranceOperations(){
 const permissions=useAuthStore(s=>s.permissions);
 const canReview=permissions.includes("review_insurance_applications"),canQuote=permissions.includes("manage_insurance_quotes"),canApprove=permissions.includes("approve_insurance_quotes"),canVerify=permissions.includes("verify_insurance_payments"),canIssue=permissions.includes("issue_insurance_policies"),canManageClaims=permissions.includes("manage_insurance_claims"),canManageRenewals=permissions.includes("manage_insurance_renewals"),canReport=permissions.includes("view_insurance_reports");
 const allowed=canReview||canQuote||canManageClaims||canManageRenewals||canReport;
 const [summary,setSummary]=useState<InsuranceOperationsSummary>({openCases:0,unassignedCases:0,paymentsAwaitingVerification:0,openClaims:0,renewalsDue:0}),[cases,setCases]=useState<InsuranceCase[]>([]),[claims,setClaims]=useState<InsuranceClaim[]>([]),[renewals,setRenewals]=useState<InsurancePolicy[]>([]),[companies,setCompanies]=useState<InsuranceCompany[]>([]),[loading,setLoading]=useState(true),[quoteCase,setQuoteCase]=useState<InsuranceCase|null>(null),[quote,setQuote]=useState(blank);
 const load=useCallback(async()=>{if(!allowed)return;setLoading(true);try{const emptyPage={content:[]};const [s,c,cl,r,co]=await Promise.all([canReport?insuranceService.operationsSummary():Promise.resolve({openCases:0,unassignedCases:0,paymentsAwaitingVerification:0,openClaims:0,renewalsDue:0}),canReview?insuranceService.operationsCases():Promise.resolve(emptyPage),canManageClaims?insuranceService.operationsClaims():Promise.resolve(emptyPage),canManageRenewals?insuranceService.operationsRenewals():Promise.resolve(emptyPage),insuranceService.companies()]);setSummary(s);setCases(Array.isArray(c.content)?c.content:[]);setClaims(Array.isArray(cl.content)?cl.content:[]);setRenewals(Array.isArray(r.content)?r.content:[]);setCompanies(Array.isArray(co.data?.data)?co.data.data:[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Could not load insurance operations."))}finally{setLoading(false)}},[allowed,canManageClaims,canManageRenewals,canReport,canReview]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function run(action:()=>Promise<unknown>,message:string){try{await action();toast.success(message);await load()}catch(e:unknown){toast.error(apiErrorMessage(e,"Operation could not be completed."))}}
 async function addQuote(e:FormEvent){e.preventDefault();if(!quoteCase)return;await run(()=>insuranceService.addQuote(quoteCase.id,{...quote,companyId:Number(quote.companyId),basePremium:Number(quote.basePremium),taxesLevies:Number(quote.taxesLevies),totalPremium:Number(quote.totalPremium)}),"Draft quote saved.");setQuoteCase(null);setQuote(blank)}
 const metrics:[string,number,typeof FileCheck2][]=[["Open applications",summary.openCases,FileCheck2],["Unassigned",summary.unassignedCases,Users],["Payments to verify",summary.paymentsAwaitingVerification,CheckCircle2],["Open claims",summary.openClaims,ShieldCheck],["Renewals due",summary.renewalsDue,Clock]];
 if(!allowed)return <div className="mx-auto max-w-xl p-8"><Card><CardContent className="p-8 text-center"><ShieldCheck className="mx-auto size-12 text-slate-400"/><h1 className="mt-4 text-2xl font-bold">Silverwood staff access only</h1><p className="mt-2 text-muted-foreground">Switch to an assigned Insurance Adviser or Insurance Manager role.</p><Button asChild className="mt-5"><Link href="/dashboard/insurance">Return to Insurance</Link></Button></CardContent></Card></div>;
 return <div className="min-h-screen bg-slate-50 p-4 sm:p-7"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><Button variant="link" asChild className="h-auto p-0"><Link href="/dashboard/insurance"><ArrowLeft className="mr-1 size-4"/>Customer hub</Link></Button><h1 className="mt-2 text-3xl font-bold text-[#10243e]">Silverwood Insurance Operations</h1><p className="text-muted-foreground">Controlled adviser and manager workflow.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 size-4 ${loading?"animate-spin":""}`}/>Refresh</Button></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,Icon])=><Card key={label}><CardContent className="flex items-center justify-between p-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div><Icon className="size-7 text-[#1769aa]"/></CardContent></Card>)}</div>
  <Tabs defaultValue="applications" className="mt-6"><TabsList><TabsTrigger value="applications">Applications</TabsTrigger><TabsTrigger value="claims">Claims</TabsTrigger><TabsTrigger value="renewals">Renewals</TabsTrigger></TabsList>
   <TabsContent value="applications" className="space-y-4">{cases.map(c=><Card key={c.id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle>{c.reference} · {title(c.productCode)}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{c.fullName} · {c.phone} · {c.email}</p></div><Badge>{title(c.status)}</Badge></div></CardHeader><CardContent><p className="text-sm">{c.subjectDescription}</p>{c.riskDetails&&<p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm">{c.riskDetails}</p>}<div className="mt-4 flex flex-wrap gap-2">{canReview&&!c.assignedAdviserId&&<Button size="sm" variant="outline" onClick={()=>{const id=prompt("Adviser user ID");if(id)void run(()=>insuranceService.assignCase(c.id,Number(id)),"Application assigned.")}}>Assign</Button>}{canQuote&&<Button size="sm" variant="outline" onClick={()=>setQuoteCase(c)}>Add quote</Button>}{canApprove&&c.quotes.filter(q=>q.status==="DRAFT").map(q=><Button key={q.id} size="sm" onClick={()=>void run(()=>insuranceService.publishQuote(c.id,q.id),"Quote approved and published.")}>Approve {q.companyName}</Button>)}{canVerify&&c.payments.filter(p=>p.status==="PENDING_VERIFICATION").map(p=><span key={p.id} className="flex gap-2"><Button size="sm" disabled={!p.proofAvailable} onClick={()=>void run(()=>insuranceService.decidePayment(p.id,"VERIFIED"),"Payment verified.")}>Verify payment</Button><Button size="sm" variant="destructive" onClick={()=>{const reason=prompt("Rejection reason");if(reason)void run(()=>insuranceService.decidePayment(p.id,"REJECTED",reason),"Payment rejected.")}}>Reject</Button></span>)}{canVerify&&c.payments.filter(p=>p.status==="VERIFIED").map(p=><Button key={p.id} size="sm" onClick={()=>{const ref=prompt("Insurer remittance reference");if(ref)void run(()=>insuranceService.remitPayment(p.id,ref),"Premium remittance recorded.")}}>Record remittance</Button>)}{canIssue&&c.status==="PREMIUM_REMITTED"&&<Button size="sm" onClick={()=>{const policyNumber=prompt("Policy number"),startDate=prompt("Start date (YYYY-MM-DD)"),endDate=prompt("End date (YYYY-MM-DD)");if(policyNumber&&startDate&&endDate)void run(()=>insuranceService.issuePolicy(c.id,{policyNumber,startDate,endDate}),"Policy issued.")}}>Issue policy</Button>}</div></CardContent></Card>)}{!cases.length&&<p className="p-6 text-sm text-muted-foreground">No applications in the queue.</p>}</TabsContent>
   <TabsContent value="claims" className="space-y-3">{claims.map(c=><Card key={c.id}><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{c.reference} · {c.policyNumber}</h3><p className="mt-1 text-sm">{c.description}</p><p className="mt-1 text-xs text-muted-foreground">Incident: {new Date(c.incidentAt).toLocaleString("en-KE")}</p></div><div className="w-52"><Select value={c.status} onValueChange={status=>{const note=prompt("Status note (optional)")??undefined;void run(()=>insuranceService.updateClaim(c.id,{status,note}),"Claim status updated.")}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["ACKNOWLEDGED","DOCS_REQUIRED","SENT_TO_INSURER","ASSESSED","APPROVED","DECLINED","SETTLED","CLOSED"].map(s=><SelectItem key={s} value={s}>{title(s)}</SelectItem>)}</SelectContent></Select></div></div></CardContent></Card>)}</TabsContent>
   <TabsContent value="renewals" className="space-y-3">{renewals.map(p=><Card key={p.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="font-bold">{p.policyNumber} · {p.companyName}</h3><p className="text-sm text-muted-foreground">Ends {p.endDate}</p></div><Select value={p.renewalStatus} onValueChange={status=>void run(()=>insuranceService.updateRenewal(p.id,status),"Renewal status updated.")}><SelectTrigger className="w-52"><SelectValue/></SelectTrigger><SelectContent>{["CONTACTED","RENEWAL_QUOTED","ACCEPTED","PAID","RENEWED","LAPSED"].map(s=><SelectItem key={s} value={s}>{title(s)}</SelectItem>)}</SelectContent></Select></CardContent></Card>)}</TabsContent>
  </Tabs></div>
  <Dialog open={!!quoteCase} onOpenChange={o=>!o&&setQuoteCase(null)}><DialogContent><form onSubmit={addQuote}><DialogHeader><DialogTitle>Add insurer quotation</DialogTitle><DialogDescription>Save a draft. An Insurance Manager must approve it before the customer can see it.</DialogDescription></DialogHeader><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Insurer"><Select required value={quote.companyId} onValueChange={companyId=>setQuote({...quote,companyId})}><SelectTrigger><SelectValue placeholder="Select insurer"/></SelectTrigger><SelectContent>{companies.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Quote number"><Input value={quote.quoteNumber} onChange={e=>setQuote({...quote,quoteNumber:e.target.value})}/></Field><Field label="Base premium"><Input required type="number" min="0" step="0.01" value={quote.basePremium} onChange={e=>setQuote({...quote,basePremium:e.target.value})}/></Field><Field label="Taxes and levies"><Input required type="number" min="0" step="0.01" value={quote.taxesLevies} onChange={e=>setQuote({...quote,taxesLevies:e.target.value})}/></Field><Field label="Total premium"><Input required type="number" min="0.01" step="0.01" value={quote.totalPremium} onChange={e=>setQuote({...quote,totalPremium:e.target.value})}/></Field><Field label="Valid until"><Input required type="date" min={new Date().toISOString().slice(0,10)} value={quote.validUntil} onChange={e=>setQuote({...quote,validUntil:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="Coverage summary"><Textarea required value={quote.coverageSummary} onChange={e=>setQuote({...quote,coverageSummary:e.target.value})}/></Field></div><div className="sm:col-span-2"><Field label="Excess details"><Textarea value={quote.excessDetails} onChange={e=>setQuote({...quote,excessDetails:e.target.value})}/></Field></div></div><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={()=>setQuoteCase(null)}>Cancel</Button><Button>Save draft</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
