"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {toast} from "sonner";
import {AlertTriangle,Archive,ArrowUpRight,Building2,CalendarClock,FileLock2,Goal,Landmark,Plus,RefreshCw,Scale,ShieldCheck,Sparkles,TrendingUp,WalletCards} from "lucide-react";
import {wealthService,AssetPayload,WealthPropertyOption} from "@/services/wealth.service";
import {WealthAsset,WealthDashboard,VaultDocument} from "@/types/wealth";
import {apiErrorMessage} from "@/lib/api-error";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Badge} from "@/components/ui/badge";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";

const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number,c="KES")=>new Intl.NumberFormat("en-KE",{style:"currency",currency:c,maximumFractionDigits:0}).format(n||0);
const emptyAsset:AssetPayload={assetType:"PROPERTY",name:"",currency:"KES",acquisitionCost:0,currentValue:0,valuationDate:today(),status:"ACTIVE"};

export default function WealthPage(){
 const [dashboard,setDashboard]=useState<WealthDashboard|null>(null),[assets,setAssets]=useState<WealthAsset[]>([]),[busy,setBusy]=useState(false);
 const [propertyOptions,setPropertyOptions]=useState<WealthPropertyOption[]>([]);
 const [selected,setSelected]=useState<number|undefined>(),[assetForm,setAssetForm]=useState<AssetPayload>(emptyAsset),[editing,setEditing]=useState<number>();
 const [years,setYears]=useState(5),[valueGrowth,setValueGrowth]=useState(5),[incomeGrowth,setIncomeGrowth]=useState(3),[expenseGrowth,setExpenseGrowth]=useState(3);
 const [docs,setDocs]=useState<VaultDocument[]>([]);
 const selectedAsset=useMemo(()=>assets.find(a=>a.id===selected),[assets,selected]);
 const load=useCallback(async()=>{try{const [d,a,p]=await Promise.all([wealthService.dashboard(years,valueGrowth,incomeGrowth,expenseGrowth),wealthService.assets(),wealthService.propertyOptions().catch(()=>({data:{data:[]}}))]);setDashboard(d.data?.data);const next=a.data?.data??[];setAssets(next);setPropertyOptions((p.data?.data??[]) as WealthPropertyOption[]);setSelected(v=>v??next[0]?.id)}catch(e:unknown){toast.error(apiErrorMessage(e,"Could not load Wealth."))}},[years,valueGrowth,incomeGrowth,expenseGrowth]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!selected){setDocs([]);return}wealthService.documents(selected).then(r=>setDocs(r.data?.data??[])).catch(()=>setDocs([]))},[selected]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);try{await action();toast.success(success);await load()}catch(e:unknown){toast.error(apiErrorMessage(e,"Wealth update failed."))}finally{setBusy(false)}}
 function submitAsset(e:FormEvent){e.preventDefault();run(()=>editing?wealthService.updateAsset(editing,assetForm):wealthService.createAsset(assetForm),editing?"Asset updated; valuation history preserved.":"Asset added to Wealth.");setAssetForm(emptyAsset);setEditing(undefined)}
 function editAsset(a:WealthAsset){setEditing(a.id);setAssetForm({propertyId:a.propertyId,assetType:a.assetType,name:a.name,reference:a.reference,location:a.location,currency:a.currency,acquisitionCost:a.acquisitionCost,acquisitionDate:a.acquisitionDate,currentValue:a.currentValue,valuationDate:a.valuationDate,status:a.status});}
 const s=dashboard?.summary;
 return <div className="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6">
  <section className="overflow-hidden rounded-3xl bg-[#08184A] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#FF7A50]"><Sparkles className="size-4"/>My Wealth</div><h1 className="text-3xl font-bold sm:text-5xl">Your financial command centre.</h1><p className="mt-3 text-white/70">Know what you own, what it is worth, what it earns, what it costs, what needs attention—and how your wealth is growing.</p></div><Button onClick={load} variant="secondary"><RefreshCw className="mr-2 size-4"/>Refresh</Button></div></section>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-8">{[
   ["Net worth",money(s?.netWorth??0,s?.currency),WalletCards],["Asset value",money(s?.totalAssetValue??0,s?.currency),Landmark],["Equity",money(s?.equity??0,s?.currency),Scale],["Annual NOI",money(s?.netOperatingIncome??0,s?.currency),TrendingUp],["Yield",`${s?.portfolioYieldPercent??0}%`,ArrowUpRight],["Occupancy",`${s?.occupancyPercent??0}%`,Building2],["Arrears",money(s?.arrears??0,s?.currency),AlertTriangle],["Deadlines",`${s?.overdueDeadlines??0} overdue`,CalendarClock]
  ].map(([label,value,Icon])=><Card key={String(label)}><CardContent className="pt-5"><div className="mb-3 flex size-9 items-center justify-center rounded-xl bg-orange-50 text-[#EF4217]"><Icon className="size-5"/></div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{String(label)}</p><p className="mt-1 text-xl font-bold">{String(value)}</p></CardContent></Card>)}</div>
  <PropertyConnector options={propertyOptions} linked={new Set(assets.map(asset=>asset.propertyId).filter((id):id is number=>Boolean(id)))} busy={busy} run={run}/>
  <Tabs defaultValue="overview" className="space-y-5"><TabsList className="h-auto flex-wrap justify-start"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="assets">Assets</TabsTrigger><TabsTrigger value="finance">Income & debt</TabsTrigger><TabsTrigger value="compliance">Lifecycle</TabsTrigger><TabsTrigger value="vault">Asset vault</TabsTrigger><TabsTrigger value="goals">Goals & projections</TabsTrigger></TabsList>
   <TabsContent value="overview" className="grid gap-5 lg:grid-cols-[1.6fr_1fr]">
    <Card><CardHeader><CardTitle>Asset performance</CardTitle><CardDescription>Live rental operations combine with annual cash activity, value, equity, yield, leverage and concentration.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-3">Asset</th><th>Value</th><th>Income</th><th>NOI</th><th>Yield</th><th>Occupancy</th><th>Arrears</th><th>LTV</th><th>Equity</th><th>Share</th></tr></thead><tbody>{dashboard?.assets.map(a=><tr key={a.assetId} className="border-b last:border-0"><td className="py-4"><strong>{a.name}</strong><div className="text-xs text-muted-foreground">{a.assetType}</div></td><td>{money(a.value,a.currency)}</td><td>{money(a.income,a.currency)}</td><td className={a.netOperatingIncome<0?"text-red-600":"text-emerald-700"}>{money(a.netOperatingIncome,a.currency)}</td><td>{a.rentalYieldPercent}%</td><td>{a.totalUnits?`${a.occupancyPercent}% (${a.occupiedUnits}/${a.totalUnits})`:"—"}</td><td className={a.arrears>0?"text-red-600":""}>{money(a.arrears,a.currency)}</td><td>{a.loanToValuePercent}%</td><td>{money(a.equity,a.currency)}</td><td>{a.concentrationPercent}%</td></tr>)}</tbody></table>{!dashboard?.assets.length&&<Empty text="Add your first asset to begin measuring wealth."/>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-5 text-[#EF4217]"/>Intelligent attention list</CardTitle><CardDescription>Explainable signals—not financial advice.</CardDescription></CardHeader><CardContent className="space-y-3">{dashboard?.insights.map((i,index)=><div key={`${i.code}-${index}`} className="rounded-xl border p-4"><div className="flex items-start gap-3"><AlertTriangle className={`mt-0.5 size-4 ${i.severity==="HIGH"?"text-red-600":i.severity==="MEDIUM"?"text-amber-600":"text-blue-600"}`}/><div><div className="flex flex-wrap items-center gap-2"><strong>{i.title}</strong><Badge variant="outline">{i.severity}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{i.explanation}</p><p className="mt-2 text-sm font-medium">Next: {i.recommendedAction}</p></div></div></div>)}</CardContent></Card>
   </TabsContent>
   <TabsContent value="assets" className="grid gap-5 lg:grid-cols-[1fr_1.2fr]">
    <Card><CardHeader><CardTitle>{editing?"Edit asset":"Add an asset"}</CardTitle><CardDescription>Property, land, business, cash, investment or another valuable asset.</CardDescription></CardHeader><CardContent><form onSubmit={submitAsset} className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input required value={assetForm.name} onChange={e=>setAssetForm({...assetForm,name:e.target.value})}/></Field><Field label="Type"><select className="h-9 w-full rounded-md border bg-transparent px-3" value={assetForm.assetType} onChange={e=>setAssetForm({...assetForm,assetType:e.target.value})}>{["PROPERTY","LAND","BUSINESS","INVESTMENT","CASH","VEHICLE","OTHER"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Current value"><Input required min="0" type="number" value={assetForm.currentValue} onChange={e=>setAssetForm({...assetForm,currentValue:Number(e.target.value)})}/></Field><Field label="Acquisition cost"><Input min="0" type="number" value={assetForm.acquisitionCost} onChange={e=>setAssetForm({...assetForm,acquisitionCost:Number(e.target.value)})}/></Field><Field label="Currency"><Input maxLength={3} value={assetForm.currency} onChange={e=>setAssetForm({...assetForm,currency:e.target.value.toUpperCase()})}/></Field><Field label="Valuation date"><Input required type="date" value={assetForm.valuationDate} onChange={e=>setAssetForm({...assetForm,valuationDate:e.target.value})}/></Field><Field label="Reference"><Input value={assetForm.reference??""} onChange={e=>setAssetForm({...assetForm,reference:e.target.value})}/></Field><Field label="Location"><Input value={assetForm.location??""} onChange={e=>setAssetForm({...assetForm,location:e.target.value})}/></Field><div className="flex gap-2 sm:col-span-2"><Button disabled={busy} className="bg-[#EF4217]"><Plus className="mr-2 size-4"/>{editing?"Save asset":"Add asset"}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing(undefined);setAssetForm(emptyAsset)}}>Cancel</Button>}</div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>What you own</CardTitle><CardDescription>Editing value creates a valuation-history entry. Archiving never destroys history.</CardDescription></CardHeader><CardContent className="space-y-3">{assets.map(a=><div key={a.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><Building2 className="size-4 text-[#EF4217]"/><strong>{a.name}</strong><Badge variant="outline">{a.assetType}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{money(a.currentValue,a.currency)} · valued {a.valuationDate}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>editAsset(a)}>Edit</Button><Button size="sm" variant="ghost" onClick={()=>confirm("Archive this asset and retain its history?")&&run(()=>wealthService.archiveAsset(a.id),"Asset archived.")}><Archive className="size-4"/></Button></div></div>)}{!assets.length&&<Empty text="No assets yet."/>}</CardContent></Card>
   </TabsContent>
   <TabsContent value="finance"><AssetAction asset={selectedAsset} assets={assets} selected={selected} onSelect={setSelected}><FinanceForms asset={selectedAsset} busy={busy} run={run}/></AssetAction></TabsContent>
   <TabsContent value="compliance"><AssetAction asset={selectedAsset} assets={assets} selected={selected} onSelect={setSelected}><Compliance asset={selectedAsset} obligations={dashboard?.obligations??[]} busy={busy} run={run}/></AssetAction></TabsContent>
   <TabsContent value="vault"><AssetAction asset={selectedAsset} assets={assets} selected={selected} onSelect={setSelected}><Vault asset={selectedAsset} docs={docs} busy={busy} run={async(a,m)=>{await run(a,m);if(selected){const r=await wealthService.documents(selected);setDocs(r.data?.data??[])}}}/></AssetAction></TabsContent>
   <TabsContent value="goals" className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><Goals busy={busy} progress={dashboard?.goalProgress??[]} run={run}/><Card><CardHeader><CardTitle>Scenario projection</CardTitle><CardDescription>Adjust transparent assumptions. Projections are estimates, not guarantees.</CardDescription></CardHeader><CardContent><div className="mb-5 grid gap-3 sm:grid-cols-4"><Field label="Years"><Input type="number" min="1" max="30" value={years} onChange={e=>setYears(Number(e.target.value))}/></Field><Field label="Value growth %"><Input type="number" step=".1" value={valueGrowth} onChange={e=>setValueGrowth(Number(e.target.value))}/></Field><Field label="Income growth %"><Input type="number" step=".1" value={incomeGrowth} onChange={e=>setIncomeGrowth(Number(e.target.value))}/></Field><Field label="Expense growth %"><Input type="number" step=".1" value={expenseGrowth} onChange={e=>setExpenseGrowth(Number(e.target.value))}/></Field></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b text-left"><th className="pb-3">Year</th><th>Asset value</th><th>Net worth</th><th>Income</th><th>Expenses</th><th>Cash flow</th></tr></thead><tbody>{dashboard?.projection.map(p=><tr className="border-b" key={p.year}><td className="py-3">{p.year}</td><td>{money(p.assetValue,s?.currency)}</td><td>{money(p.netWorth,s?.currency)}</td><td>{money(p.income,s?.currency)}</td><td>{money(p.expenses,s?.currency)}</td><td>{money(p.cashFlow,s?.currency)}</td></tr>)}</tbody></table></div></CardContent></Card></TabsContent>
  </Tabs>
 </div>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Empty({text}:{text:string}){return <p className="py-10 text-center text-sm text-muted-foreground">{text}</p>}
function PropertyConnector({options,linked,busy,run}:{options:WealthPropertyOption[];linked:Set<number>;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>void}){const available=options.filter(option=>!linked.has(option.id));const [propertyId,setPropertyId]=useState<number>(),[currentValue,setCurrentValue]=useState(0),[acquisitionCost,setAcquisitionCost]=useState(0);if(!available.length)return null;const property=available.find(option=>option.id===propertyId);return <Card className="border-emerald-200 bg-emerald-50/30"><CardHeader><CardTitle>Connect your live property operations</CardTitle><CardDescription>One secure link brings units, occupancy and outstanding rent into My Wealth. Existing property records are not duplicated.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[1.4fr_1fr_1fr_auto] md:items-end" onSubmit={event=>{event.preventDefault();if(!property)return;run(()=>wealthService.createAsset({propertyId:property.id,assetType:"PROPERTY",name:property.name,location:property.description,currency:"KES",acquisitionCost,currentValue,valuationDate:today(),status:"ACTIVE"}),"Property connected to My Wealth.");setPropertyId(undefined);setCurrentValue(0);setAcquisitionCost(0)}}><Field label="Managed property"><select required className="h-9 w-full rounded-md border bg-white px-3" value={propertyId??""} onChange={event=>setPropertyId(Number(event.target.value))}><option value="">Select a property</option>{available.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></Field><Field label="Current value"><Input required min="0" type="number" value={currentValue} onChange={event=>setCurrentValue(Number(event.target.value))}/></Field><Field label="Acquisition cost"><Input min="0" type="number" value={acquisitionCost} onChange={event=>setAcquisitionCost(Number(event.target.value))}/></Field><Button disabled={busy||!propertyId} className="bg-emerald-700 hover:bg-emerald-800">Connect property</Button></form></CardContent></Card>}
function AssetAction({asset,assets,selected,onSelect,children}:{asset?:WealthAsset;assets:WealthAsset[];selected?:number;onSelect:(n:number)=>void;children:React.ReactNode}){return <div className="space-y-5"><Card><CardContent className="flex flex-col gap-3 pt-5 sm:flex-row sm:items-center"><Label>Work on asset</Label><select className="h-10 min-w-64 rounded-md border bg-transparent px-3" value={selected??""} onChange={e=>onSelect(Number(e.target.value))}><option value="">Select asset</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{asset&&<Badge>{asset.currency} {asset.currentValue.toLocaleString()}</Badge>}</CardContent></Card>{asset?children:<Empty text="Add or select an asset first."/>}</div>}
function FinanceForms({asset,busy,run}:{asset?:WealthAsset;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>void}){const [flow,setFlow]=useState({flowType:"INCOME" as "INCOME"|"EXPENSE",category:"RENT",amount:0,entryDate:today(),description:"",recurring:false});const [debt,setDebt]=useState({lender:"",currency:"KES",originalPrincipal:0,outstandingPrincipal:0,annualInterestRate:0,monthlyPayment:0});if(!asset)return null;return <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Record income or expense</CardTitle><CardDescription>Use actual entries to calculate NOI, yield and cash flow.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run(()=>wealthService.addCashFlow(asset.id,flow),"Cash flow recorded.")}}><Field label="Flow"><select className="h-9 w-full rounded-md border bg-transparent px-3" value={flow.flowType} onChange={e=>setFlow({...flow,flowType:e.target.value as "INCOME"|"EXPENSE"})}><option>INCOME</option><option>EXPENSE</option></select></Field><Field label="Category"><Input value={flow.category} onChange={e=>setFlow({...flow,category:e.target.value.toUpperCase()})}/></Field><Field label="Amount"><Input required min=".01" type="number" value={flow.amount} onChange={e=>setFlow({...flow,amount:Number(e.target.value)})}/></Field><Field label="Date"><Input required type="date" value={flow.entryDate} onChange={e=>setFlow({...flow,entryDate:e.target.value})}/></Field><Button disabled={busy}>Record cash flow</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Add mortgage or debt</CardTitle><CardDescription>Outstanding principal drives LTV, equity and net worth.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run(()=>wealthService.addLiability(asset.id,debt),"Liability added.")}}><Field label="Lender"><Input required value={debt.lender} onChange={e=>setDebt({...debt,lender:e.target.value})}/></Field><Field label="Currency"><Input value={debt.currency} onChange={e=>setDebt({...debt,currency:e.target.value.toUpperCase()})}/></Field><Field label="Original principal"><Input required min="0" type="number" value={debt.originalPrincipal} onChange={e=>setDebt({...debt,originalPrincipal:Number(e.target.value)})}/></Field><Field label="Outstanding"><Input required min="0" type="number" value={debt.outstandingPrincipal} onChange={e=>setDebt({...debt,outstandingPrincipal:Number(e.target.value)})}/></Field><Field label="Interest %"><Input min="0" type="number" step=".01" value={debt.annualInterestRate} onChange={e=>setDebt({...debt,annualInterestRate:Number(e.target.value)})}/></Field><Field label="Monthly payment"><Input min="0" type="number" value={debt.monthlyPayment} onChange={e=>setDebt({...debt,monthlyPayment:Number(e.target.value)})}/></Field><Button disabled={busy}>Add liability</Button></form></CardContent></Card></div>}
function Compliance({asset,obligations,busy,run}:{asset?:WealthAsset;obligations:WealthDashboard["obligations"];busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>void}){const [f,setF]=useState({obligationType:"INSURANCE",title:"",dueDate:"",expiryDate:"",currency:"KES",reminderDays:30,notes:""});if(!asset)return null;const rows=obligations.filter(o=>o.assetId===asset.id);return <div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><Card><CardHeader><CardTitle>Track a deadline</CardTitle><CardDescription>Leases, insurance, licences, permits, rates, land rent, service charges, warranties, inspections and maintenance.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run(()=>wealthService.addObligation(asset.id,f),"Deadline added.")}}><Field label="Type"><Input value={f.obligationType} onChange={e=>setF({...f,obligationType:e.target.value.toUpperCase()})}/></Field><Field label="Title"><Input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></Field><Field label="Expiry date"><Input type="date" value={f.expiryDate} onChange={e=>setF({...f,expiryDate:e.target.value})}/></Field><Field label="Remind days before"><Input min="0" max="365" type="number" value={f.reminderDays} onChange={e=>setF({...f,reminderDays:Number(e.target.value)})}/></Field><Button disabled={busy}>Track deadline</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Lifecycle register</CardTitle></CardHeader><CardContent className="space-y-3">{rows.map(o=><div className="flex items-center justify-between rounded-xl border p-4" key={o.id}><div><div className="flex gap-2"><ShieldCheck className="size-4 text-[#EF4217]"/><strong>{o.title}</strong><Badge variant="outline">{o.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{o.obligationType} · {o.expiryDate?`Expires ${o.expiryDate}`:o.dueDate?`Due ${o.dueDate}`:"No deadline"}</p></div>{o.status!=="COMPLETED"&&<Button size="sm" variant="outline" onClick={()=>run(()=>wealthService.completeObligation(o.id),"Marked complete.")}>Complete</Button>}</div>)}{!rows.length&&<Empty text="No lifecycle obligations for this asset."/>}</CardContent></Card></div>}
function Vault({asset,docs,busy,run}:{asset?:WealthAsset;docs:VaultDocument[];busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>void}){const [category,setCategory]=useState("TITLE_DOCUMENT"),[file,setFile]=useState<File>();if(!asset)return null;return <div className="grid gap-5 lg:grid-cols-[1fr_1.3fr]"><Card><CardHeader><CardTitle className="flex gap-2"><FileLock2 className="size-5"/>Secure asset vault</CardTitle><CardDescription>Private storage, owner-scoped access, SHA-256 integrity record and short-lived download links. Maximum 20 MB.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!file)return;const d=new FormData();d.append("category",category);d.append("file",file);run(()=>wealthService.uploadDocument(asset.id,d),"Document secured in the vault.")}}><Field label="Document category"><Input value={category} onChange={e=>setCategory(e.target.value.toUpperCase())}/></Field><Field label="File"><Input required type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0])}/></Field><Button disabled={busy||!file}>Upload securely</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Asset record</CardTitle><CardDescription>Titles, sale agreements, valuations, policies, leases, approvals and warranties.</CardDescription></CardHeader><CardContent className="space-y-3">{docs.map(({document:d,downloadUrl})=><a key={d.id} href={downloadUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border p-4 hover:border-[#EF4217]"><div><strong>{d.displayName}</strong><p className="text-sm text-muted-foreground">{d.category} · {(d.fileSize/1024).toFixed(0)} KB</p></div><FileLock2 className="size-5 text-[#EF4217]"/></a>)}{!docs.length&&<Empty text="No documents in this asset vault."/>}</CardContent></Card></div>}
function Goals({busy,progress,run}:{busy:boolean;progress:WealthDashboard["goalProgress"];run:(a:()=>Promise<unknown>,m:string)=>void}){const [f,setF]=useState({goalType:"NET_WORTH",name:"",targetAmount:0,currency:"KES",targetDate:new Date(Date.now()+365*86400000).toISOString().slice(0,10)});return <Card><CardHeader><CardTitle className="flex gap-2"><Goal className="size-5"/>Wealth goals</CardTitle><CardDescription>Set a measurable net-worth, income, equity or debt-reduction target.</CardDescription></CardHeader><CardContent><form className="mb-6 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run(()=>wealthService.addGoal(f),"Wealth goal created.")}}><Field label="Goal name"><Input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Metric"><select className="h-9 w-full rounded-md border bg-transparent px-3" value={f.goalType} onChange={e=>setF({...f,goalType:e.target.value})}>{["NET_WORTH","INCOME","EQUITY","DEBT_REDUCTION"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Target"><Input required min="1" type="number" value={f.targetAmount} onChange={e=>setF({...f,targetAmount:Number(e.target.value)})}/></Field><Field label="Target date"><Input required type="date" value={f.targetDate} onChange={e=>setF({...f,targetDate:e.target.value})}/></Field><Button disabled={busy}>Set goal</Button></form><div className="space-y-4">{progress.map(g=><div key={g.goalId}><div className="mb-1 flex justify-between text-sm"><strong>{g.name}</strong><span>{Math.min(g.progressPercent,100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-[#EF4217]" style={{width:`${Math.min(g.progressPercent,100)}%`}}/></div><p className="mt-1 text-xs text-muted-foreground">{money(g.currentAmount)} of {money(g.targetAmount)} by {g.targetDate}</p></div>)}</div></CardContent></Card>}
