"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw, ShieldCheck, ShieldX, Truck } from "lucide-react";
import { toast } from "sonner";
import { decideSokoRider, sokoAdminRiders, SokoRider } from "@/services/soko";

const error=(e:unknown,fallback:string)=>(e as {response?:{data?:{description?:string}}}).response?.data?.description??fallback;
export default function RiderVerificationPage(){
 const [rows,setRows]=useState<SokoRider[]>([]),[busy,setBusy]=useState<number>(),[query,setQuery]=useState("");
 const load=useCallback(async()=>{try{const r=await sokoAdminRiders();setRows(r.data?.data??[]);}catch(e){toast.error(error(e,"Riders could not be loaded."));}},[]);useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>rows.filter(r=>!query.trim()||`${r.displayName} ${r.email} ${r.phoneNumber} ${r.vehiclePlate}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const decide=async(r:SokoRider,decision:"VERIFY"|"SUSPEND"|"REJECT")=>{const reason=decision==="VERIFY"?undefined:prompt(`Reason to ${decision.toLowerCase()} ${r.displayName}:`);if(decision!=="VERIFY"&&!reason?.trim())return;setBusy(r.id);try{await decideSokoRider(r.id,decision,reason?.trim());toast.success(`${r.displayName} updated.`);await load();}catch(e){toast.error(error(e,"Rider decision could not be saved."));}finally{setBusy(undefined);}};
 return <div className="space-y-5 px-3 py-6"><header className="rounded-3xl bg-[#07143D] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-300">Marketplace trust and safety</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Rider verification</h1><p className="mt-2 text-white/70">A rider must have a linked SlickHood account, approved rider KYC and an active verification before assignment.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 font-semibold text-[#07143D]"><RefreshCw className="h-4 w-4"/>Refresh</button></div></header><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search rider, email, phone or vehicle" className="w-full rounded-xl border bg-white p-3"/><section className="grid gap-4 lg:grid-cols-2">{filtered.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-[#FF4B1F]"/><b>{r.displayName}</b></div><p className="mt-1 text-sm text-gray-600">{r.email||"No account email"} · {r.phoneNumber}</p><p className="text-sm text-gray-500">{[r.vehicleType,r.vehiclePlate].filter(Boolean).join(" · ")||"Vehicle not supplied"}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${r.verified?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{r.verificationStatus??r.status}</span></div><div className="mt-4 flex flex-wrap gap-2">{!r.verified&&<button disabled={busy===r.id} onClick={()=>decide(r,"VERIFY")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white"><ShieldCheck className="h-4 w-4"/>Verify and activate</button>}{r.verified&&r.status==="ACTIVE"&&<button disabled={busy===r.id} onClick={()=>decide(r,"SUSPEND")} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2 text-red-700"><ShieldX className="h-4 w-4"/>Suspend</button>}{!r.verified&&<button disabled={busy===r.id} onClick={()=>decide(r,"REJECT")} className="rounded-xl border px-4 py-2 text-red-700">Reject</button>}</div></article>)}{!filtered.length&&<p className="col-span-full rounded-2xl border bg-white py-16 text-center text-gray-500">No riders match this search.</p>}</section></div>;
}
