"use client";
import AffiliatePolicy from "@/components/affiliate/AffiliatePolicy";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {toast} from "sonner";
import {affiliatePayoutQueue,AffiliateAdminPayout,decideAffiliatePayout} from "@/services/affiliate";
import {apiErrorMessage} from "@/lib/api-error";
import AffiliateDirectory from "@/components/affiliate/AffiliateDirectory";
import RequireRole from "@/components/auth/RequireRole";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
type Row=AffiliateAdminPayout&{affiliateName?:string;affiliateEmail?:string};
const money=(n:number,c:string)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:c}).format(n);
function Workspace(){
 const loadRequest=useRef(0);
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const [query,setQuery]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(0),[pages,setPages]=useState(0),[total,setTotal]=useState(0);
 const [decision,setDecision]=useState<{row:Row;status:"PAID"|"REJECTED"}|null>(null),[paymentReference,setPaymentReference]=useState(""),[notes,setNotes]=useState("");
 const load=useCallback(async()=>{const request=++loadRequest.current;setBusy(true);setError(null);try{const r=await affiliatePayoutQueue({query:search||undefined,status:status||undefined,page});if(request!==loadRequest.current)return;setRows((r.data?.data??[]).map((row:{payout:AffiliateAdminPayout;affiliateName?:string;affiliateEmail?:string})=>({...row.payout,affiliateName:row.affiliateName,affiliateEmail:row.affiliateEmail})));setPages(r.data?.totalPages??0);setTotal(r.data?.totalElements??0);}catch(e){if(request===loadRequest.current)setError(apiErrorMessage(e,"Affiliate payout queue could not be loaded."));}finally{if(request===loadRequest.current)setBusy(false)}},[search,status,page]);
 useEffect(()=>{void load();return()=>{loadRequest.current++}},[load]);
 async function start(row:Row){if(busy)return;setBusy(true);try{await decideAffiliatePayout(row,"PROCESSING");await load();toast.success("Payout moved to processing.");}catch(e){toast.error(apiErrorMessage(e,"Payout changed or could not be updated. Refresh and verify the amount before trying again."));}finally{setBusy(false)}}
 function openDecision(row:Row,status:"PAID"|"REJECTED"){setDecision({row,status});setPaymentReference("");setNotes("")}
 async function submit(e:FormEvent){e.preventDefault();if(!decision||busy)return;setBusy(true);try{await decideAffiliatePayout(decision.row,decision.status,paymentReference.trim()||undefined,notes.trim()||undefined);setDecision(null);await load();toast.success("Payout decision recorded.");}catch(e){toast.error(apiErrorMessage(e,"Payout changed or could not be updated. Refresh and verify the amount before trying again."));}finally{setBusy(false)}}
 return <div className="space-y-6 p-4 sm:p-6"><header><h1 className="text-3xl font-bold text-[#162B63]">Affiliate Management</h1><p>Manage affiliate programme settings and review external payout records without moving funds automatically.</p></header><AffiliatePolicy/><AffiliateDirectory/>
 <section id="affiliate-payouts" className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Affiliate payments</h2><p className="text-sm text-slate-500">Process payout requests and mark paid only after confirming the external settlement reference. SlickHood records the payment but does not move funds. Rejection releases reserved earnings; it does not issue a refund.</p>
 <form onSubmit={e=>{e.preventDefault();setSearch(query.trim());setPage(0)}} className="flex flex-wrap gap-3"><Input aria-label="Search affiliate payouts" value={query} maxLength={160} onChange={e=>setQuery(e.target.value)} placeholder="Affiliate name, email or payout number" className="max-w-sm"/><select aria-label="Affiliate payout status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}} className="rounded border p-2"><option value="">All payout statuses</option>{["REQUESTED","PROCESSING","PAID","REJECTED"].map(s=><option key={s} value={s}>{s}</option>)}</select><Button disabled={busy}>Search payouts</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>void load()}>Refresh payouts</Button></form>
 {error?<div role="alert">{error}<Button variant="outline" onClick={()=>void load()}>Retry payouts</Button></div>:busy?<p>Loading payouts…</p>:<><p>{total} payout requests</p>{rows.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-4 rounded border p-4"><div><b>{p.payoutNumber} · {p.status}</b><p>{p.affiliateName??`Affiliate #${p.affiliateUserId}`} · {p.affiliateEmail}</p><p>{p.payoutAccountName??"Verified payout account"} · {p.payoutChannel} · account #{p.paymentAccountId??"not recorded"}</p><p>{money(p.amount,p.currency)}</p>{p.paymentReference&&<p>External reference: {p.paymentReference}</p>}{p.notes&&<p>{p.notes}</p>}</div><div className="flex gap-2">{p.status==="REQUESTED"&&<Button disabled={busy} variant="outline" onClick={()=>void start(p)}>Start processing</Button>}{["REQUESTED","PROCESSING"].includes(p.status)&&<><Button disabled={busy} variant="destructive" onClick={()=>openDecision(p,"REJECTED")}>Reject</Button><Button disabled={busy} onClick={()=>openDecision(p,"PAID")}>Mark paid</Button></>}</div></div>)}{!rows.length&&<p>No payout requests match these filters.</p>}</>}
 <div className="flex items-center gap-3"><Button variant="outline" disabled={busy||page===0} onClick={()=>setPage(page-1)}>Previous payouts</Button><p>Page {pages?page+1:0} / {pages}</p><Button variant="outline" disabled={busy||page+1>=pages} onClick={()=>setPage(page+1)}>Next payouts</Button></div></section>
 <Dialog open={!!decision} onOpenChange={v=>{if(!v&&!busy)setDecision(null)}}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{decision?.status==="PAID"?"Confirm payout settlement":"Reject payout request"}</DialogTitle><DialogDescription>{decision?.status==="PAID"?"Record the verified external payment reference. This settles the reserved commission records; SlickHood does not transfer money.":"Give a rejection reason. Reserved earnings return to the affiliate balance."}</DialogDescription></DialogHeader>{decision&&<div className="my-4 rounded-lg border bg-slate-50 p-4"><b>{decision.row.affiliateName??`Affiliate #${decision.row.affiliateUserId}`}</b><p>{money(decision.row.amount,decision.row.currency)} · {decision.row.payoutAccountName??"Verified payout account"} · {decision.row.payoutChannel}</p><p className="text-xs text-slate-500">Request {decision.row.payoutNumber}. The server rejects this decision if the amount changed after this screen opened.</p></div>}<div className="my-4 space-y-3">{decision?.status==="PAID"&&<><Label htmlFor="affiliate-payment-reference">Payment reference</Label><Input id="affiliate-payment-reference" required minLength={2} maxLength={100} disabled={busy} value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/></>}<Label htmlFor="affiliate-decision-notes">{decision?.status==="REJECTED"?"Rejection reason":"Notes (optional)"}</Label><Textarea id="affiliate-decision-notes" required={decision?.status==="REJECTED"} maxLength={1000} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)}/></div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={()=>setDecision(null)}>Cancel</Button><Button disabled={busy}>{decision?.status==="PAID"?"Confirm paid":"Reject and release earnings"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
export default function AffiliateManagement(){return <RequireRole roles={["Superadmin","Super Admin"]}><Workspace/></RequireRole>}
