"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {BadgeDollarSign,RefreshCw} from "lucide-react";
import {toast} from "sonner";
import {affiliateAdminPayouts,AffiliateAdminPayout,decideAffiliatePayout} from "@/services/affiliate";
import {apiErrorMessage} from "@/lib/api-error";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";

const money=(n:number,c:string)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:c}).format(n);

export default function AffiliateManagement(){
 const [rows,setRows]=useState<AffiliateAdminPayout[]>([]),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false);
 const [decision,setDecision]=useState<{row:AffiliateAdminPayout;status:"PAID"|"REJECTED"}|null>(null);
 const [paymentReference,setPaymentReference]=useState(""),[notes,setNotes]=useState("");
 const load=useCallback(async()=>{setBusy(true);setFailed(false);try{const r=await affiliateAdminPayouts();setRows(Array.isArray(r.data?.data)?r.data.data:[]);}catch(e:unknown){setFailed(true);toast.error(apiErrorMessage(e,"Affiliate payouts could not be loaded."));}finally{setBusy(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function start(row:AffiliateAdminPayout){setBusy(true);try{await decideAffiliatePayout(row.id,"PROCESSING");toast.success("Payout moved to processing.");await load();}catch(e:unknown){toast.error(apiErrorMessage(e,"Payout could not be updated."));}finally{setBusy(false)}}
 function openDecision(row:AffiliateAdminPayout,status:"PAID"|"REJECTED"){setDecision({row,status});setPaymentReference("");setNotes("")}
 async function submit(event:FormEvent){event.preventDefault();if(!decision)return;setBusy(true);try{await decideAffiliatePayout(decision.row.id,decision.status,paymentReference.trim()||undefined,notes.trim()||undefined);toast.success(`Payout marked ${decision.status.toLowerCase()}.`);setDecision(null);await load();}catch(e:unknown){toast.error(apiErrorMessage(e,"Payout could not be updated."));}finally{setBusy(false)}}
 return <div className="space-y-6 px-3 py-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#FF4B1F]">Affiliate operations</p><h1 className="mt-1 text-3xl font-bold text-[#162B63]">Payout management</h1><p className="text-slate-500">Review and settle reserved affiliate earnings with an auditable payment reference.</p></div><Button onClick={()=>void load()} variant="outline" disabled={busy}><RefreshCw className={`mr-2 h-4 w-4 ${busy?"animate-spin":""}`}/>Refresh</Button></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><BadgeDollarSign className="h-5 w-5 text-[#FF4B1F]"/>Payout queue</CardTitle><CardDescription>Verified account details are captured when a request is created. Rejected requests release reserved earnings.</CardDescription></CardHeader><CardContent className="space-y-3">{rows.map(p=><div key={p.id} className="flex flex-col justify-between gap-4 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{p.payoutNumber}</b><Badge variant="secondary">{p.status}</Badge></div><p className="mt-1 text-sm text-slate-500">Affiliate #{p.affiliateUserId} · {p.payoutAccountName||"Verified payout account"}{p.payoutChannel?` · ${p.payoutChannel.replaceAll("_"," ")}`:""}</p><p className="font-semibold text-[#162B63]">{money(p.amount,p.currency)}</p>{p.paymentReference&&<p className="text-xs text-emerald-700">Reference: {p.paymentReference}</p>}{p.notes&&<p className="mt-1 max-w-2xl text-xs text-slate-500">{p.notes}</p>}</div><div className="flex flex-wrap gap-2">{p.status==="REQUESTED"&&<Button disabled={busy} onClick={()=>void start(p)} variant="outline">Start processing</Button>}{["REQUESTED","PROCESSING"].includes(p.status)&&<><Button disabled={busy} onClick={()=>openDecision(p,"REJECTED")} variant="destructive">Reject</Button><Button disabled={busy} onClick={()=>openDecision(p,"PAID")} className="bg-emerald-600 hover:bg-emerald-700">Mark paid</Button></>}</div></div>)}{!rows.length&&!failed&&<p className="py-14 text-center text-slate-500">No affiliate payout requests.</p>}{failed&&<div className="py-14 text-center"><p className="text-slate-500">The payout queue could not be loaded.</p><Button className="mt-3" variant="outline" onClick={()=>void load()}>Try again</Button></div>}</CardContent></Card>
  <Dialog open={!!decision} onOpenChange={open=>!open&&setDecision(null)}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{decision?.status==="PAID"?"Confirm payout settlement":"Reject payout request"}</DialogTitle><DialogDescription>{decision?.status==="PAID"?`Record the external payment reference for ${decision.row.payoutNumber}. This marks its reserved commissions as paid.`:`Explain why ${decision?.row.payoutNumber} cannot be paid. Its reserved commissions will return to the affiliate balance.`}</DialogDescription></DialogHeader><div className="mt-5 space-y-4">{decision?.status==="PAID"&&<div className="space-y-1.5"><Label htmlFor="affiliate-payment-reference">Payment reference</Label><Input id="affiliate-payment-reference" required minLength={2} maxLength={100} autoComplete="off" value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/></div>}<div className="space-y-1.5"><Label htmlFor="affiliate-decision-notes">{decision?.status==="REJECTED"?"Rejection reason":"Notes (optional)"}</Label><Textarea id="affiliate-decision-notes" required={decision?.status==="REJECTED"} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={()=>setDecision(null)}>Cancel</Button><Button disabled={busy} variant={decision?.status==="REJECTED"?"destructive":"default"}>{decision?.status==="PAID"?"Confirm paid":"Reject and release earnings"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>
}
