import Link from "next/link";
import { ArrowRight, BadgePercent, Building2, CheckCircle2, DoorOpen, HeartPulse, Home, Landmark, Search, ShieldCheck, ShoppingBasket, Users, WalletCards } from "lucide-react";
import PublicHeader from "@/components/public/PublicHeader";
import PublicFooter from "@/components/public/PublicFooter";
import PropertyCard from "@/components/public/PropertyCard";
import { getListings } from "@/lib/property-listings";

const ecosystem = [
  { icon: Building2, title: "Property Management", text: "Run properties, units, tenants, agreements, billing and operations from one governed workspace.", accent: "bg-orange-50 text-[#EF4217]" },
  { icon: Home, title: "Estate Management", text: "Connect homeowners, service charges, estate agreements, community funds and estate operations.", accent: "bg-emerald-50 text-emerald-700" },
  { icon: Landmark, title: "Property Sales", text: "Guide buyers from invitation and letter of offer through payment, due diligence, transfer and handover.", accent: "bg-blue-50 text-blue-700" },
  { icon: WalletCards, title: "Wealth Management", text: "Give users a clearer view of property-linked assets, goals and long-term wealth activity.", accent: "bg-violet-50 text-violet-700" },
  { icon: DoorOpen, title: "Visitor Hub", text: "Coordinate invitations, gate access, visitor records and controlled entry across managed communities.", accent: "bg-cyan-50 text-cyan-700" },
  { icon: ShoppingBasket, title: "Marketplace: Soko & Services", text: "Shop for groceries, find trusted service providers, manage orders and follow verified fulfilment and delivery.", accent: "bg-lime-50 text-lime-700" },
  { icon: HeartPulse, title: "Partner Insurance Hub", text: "Request cover through Slickhood, receive quotations from participating insurance companies, compare options and select a preferred quote.", accent: "bg-rose-50 text-rose-700", href: "/insurance" },
  { icon: BadgePercent, title: "Affiliate Network", text: "Grow Slickhood through governed referrals, transparent commissions and auditable payouts.", accent: "bg-fuchsia-50 text-fuchsia-700" },
] as const;

const audiences = [
  ["Owners & property teams", "Control rental, estate and sale operations without duplicating property records."],
  ["Residents & buyers", "Access agreements, payments, visitors, marketplace services, shopping and partner insurance from one account."],
  ["Merchants & providers", "Reach connected communities, manage work or orders, and follow fulfilment clearly."],
  ["Partners & affiliates", "Participate through governed insurance quotations, delivery and referral workflows."],
] as const;

export default async function HomePage() {
  const featured = await getListings(undefined, { size: "6" }, true);
  return <div className="min-h-screen bg-[#f7f8fb] text-[#101b3f]">
    <PublicHeader />
    <main>
      <section className="relative isolate overflow-hidden bg-[#08184A] text-white">
        <div className="absolute inset-0 -z-20 bg-[linear-gradient(125deg,#08184A_0%,#101e52_56%,#321938_100%)]" />
        <div className="absolute -right-32 -top-36 -z-10 h-[34rem] w-[34rem] rounded-full bg-[#EF4217]/25 blur-3xl" />
        <div className="absolute -bottom-48 left-[35%] -z-10 h-96 w-96 rounded-full bg-blue-500/15 blur-3xl" />
        <div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-[1.04fr_.96fr] lg:px-8 lg:py-28">
          <div className="flex flex-col justify-center"><span className="w-fit rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-orange-100">One connected living and property ecosystem</span><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[1.03] tracking-[-.035em] sm:text-6xl lg:text-7xl">Manage property. Enable communities. Grow wealth.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/72">Slickhood brings property operations, estate communities, sales, wealth, visitors, marketplace shopping and services, partner insurance and affiliate growth into one trusted digital platform.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/role" className="inline-flex items-center gap-2 rounded-full bg-[#EF4217] px-6 py-3.5 font-bold text-white shadow-lg shadow-orange-950/20 transition hover:-translate-y-0.5 hover:bg-[#d93612]">Get started with Slickhood <ArrowRight className="h-4 w-4" /></Link><Link href="#ecosystem" className="rounded-full border border-white/25 bg-white/5 px-6 py-3.5 font-bold transition hover:bg-white/10">Explore the ecosystem</Link></div><Link href="#properties" className="mt-7 inline-flex w-fit items-center gap-2 text-sm font-semibold text-white/70 hover:text-white"><Search className="h-4 w-4" /> Looking for property? Browse homes to rent and properties for sale</Link></div>
          <div className="relative mx-auto w-full max-w-xl self-center"><div className="rounded-[2rem] border border-white/15 bg-white/[.08] p-5 shadow-2xl backdrop-blur-xl sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff9c7d]">Slickhood ecosystem</p><p className="mt-1 text-xl font-bold">Connected around real life</p></div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#EF4217]"><ShieldCheck className="h-6 w-6" /></div></div><div className="mt-5 grid grid-cols-2 gap-3">{[[Building2,"Manage"],[Users,"Connect"],[WalletCards,"Grow"],[ShoppingBasket,"Access"]].map(([Icon,label])=>{const TileIcon=Icon as typeof Building2;return <div key={label as string} className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><TileIcon className="h-5 w-5 text-[#ff8e6b]"/><p className="mt-5 text-lg font-bold">{label as string}</p><p className="mt-1 text-xs text-white/55">One identity. Clear journeys.</p></div>})}</div><div className="mt-3 flex items-center gap-3 rounded-2xl bg-white p-4 text-[#101b3f]"><div className="flex -space-x-2">{["P","E","S"].map((letter,index)=><span key={letter} className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-white bg-[#eef1f8] text-xs font-black" style={{zIndex:3-index}}>{letter}</span>)}</div><div><p className="text-sm font-bold">One platform, many relationships</p><p className="text-xs text-slate-500">Owners, residents, teams and partners</p></div></div></div></div>
        </div>
      </section>

      <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-slate-200 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 lg:px-8">{[["One connected platform","Shared data across the ecosystem"],["Multi-role access","The right workspace for every user"],["End-to-end workflows","From invitation to verified completion"]].map(([title,text])=><div key={title} className="flex items-center gap-3 py-5 sm:px-6 first:sm:pl-0"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#EF4217]"/><div><p className="font-bold">{title}</p><p className="text-xs text-slate-500">{text}</p></div></div>)}</div></section>

      <section id="ecosystem" className="scroll-mt-24 bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#EF4217]">The complete platform</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">More than property search.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-600 lg:justify-self-end">Slickhood is the operating layer for the people, payments, agreements, access, services and opportunities surrounding property and community life.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ecosystem.map(({icon:Icon,title,text,accent,...item})=><article key={title} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#EF4217]/30 hover:shadow-xl hover:shadow-slate-900/5"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${accent}`}><Icon className="h-6 w-6"/></div><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><Link href={("href" in item&&item.href)||"/role"} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#EF4217]">{("href" in item&&item.href)?"Request insurance":"Enter this workspace"} <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></article>)}</div></div></section>

      <section id="businesses" className="scroll-mt-24 overflow-hidden bg-[#eef1f8] py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#EF4217]">Built for the whole network</p><h2 className="mt-4 text-4xl font-black tracking-tight">Every participant gets a purposeful workspace.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">A Slickhood account can support the user’s real responsibilities without mixing unrelated operations. Teams can invite internal users and control areas of responsibility.</p><Link href="/role" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#101b3f] px-6 py-3 font-bold text-white hover:bg-[#08184A]">Choose your role <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{audiences.map(([title,text],index)=><div key={title} className={`rounded-3xl p-6 ${index===0?"bg-[#EF4217] text-white":"bg-white"}`}><span className={`text-xs font-black uppercase tracking-[.18em] ${index===0?"text-white/65":"text-[#EF4217]"}`}>0{index+1}</span><h3 className="mt-8 text-xl font-black">{title}</h3><p className={`mt-3 text-sm leading-6 ${index===0?"text-white/78":"text-slate-600"}`}>{text}</p></div>)}</div></div></section>

      <section id="properties" className="scroll-mt-24 bg-[#f7f8fb] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#EF4217]">Property listings</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Find a property to rent or buy.</h2><p className="mt-3 max-w-2xl text-slate-600">Explore available rental and sale properties listed by owners and property managers on Slickhood.</p></div><div className="flex flex-wrap gap-3"><Link href="/properties/rent" className="rounded-full bg-[#101b3f] px-5 py-3 text-sm font-bold text-white">Homes to rent</Link><Link href="/properties/buy" className="rounded-full border border-slate-300 bg-white px-5 py-3 text-sm font-bold">Property for sale</Link></div></div>{featured.items.length?<div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{featured.items.slice(0,6).map(item=><PropertyCard key={item.slug} listing={item}/>)}</div>:<div className="mt-10 rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><Building2 className="mx-auto h-9 w-9 text-slate-400"/><p className="mt-4 font-bold">New property listings are being prepared.</p><p className="mt-2 text-sm text-slate-500">Explore the platform now or check the property catalogue again soon.</p></div>}</div></section>

      <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="relative overflow-hidden rounded-[2rem] bg-[#EF4217] p-8 text-white sm:p-12"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[48px] border-white/10"/><div className="relative flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-white/65">Your Slickhood journey</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-4xl">Bring property, community and everyday services together.</h2><p className="mt-4 max-w-2xl text-white/78">Choose the role that fits you. Slickhood will guide you to the right workspace and requirements.</p></div><div className="flex shrink-0 flex-wrap gap-3"><Link href="/role" className="rounded-full bg-white px-6 py-3.5 font-bold text-[#EF4217]">Create an account</Link><Link href="/login" className="rounded-full border border-white/30 px-6 py-3.5 font-bold">Sign in</Link></div></div></div></div></section>
    </main><PublicFooter />
  </div>;
}
