"use client";
import {useEffect,useState} from "react";
import {ArrowRight,BookOpen,Landmark,ShieldCheck,Target} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {wealthService,WealthAssetType} from "@/services/wealth.service";
import {WealthAsset,WealthDashboard,WealthLedger,WealthLiability} from "@/types/wealth";
import {envelopeItem} from "@/lib/api-envelope";
import {useAuthStore} from "@/store/authStore";

export function useWealthAccess(){const permissions=useAuthStore(state=>state.permissions);return (suffix:string)=>permissions.includes(`manage_wealth_${suffix}`);}
const money=(value:number,code="KES")=>new Intl.NumberFormat("en-KE",{style:"currency",currency:/^[A-Z]{3}$/.test(code)?code:"KES",maximumFractionDigits:2}).format(Number(value)||0);
type Run=(action:()=>Promise<unknown>,message:string)=>Promise<boolean>;

export function WealthJourney({assets,dashboard,categories,onNavigate}:{assets:WealthAsset[];dashboard:WealthDashboard|null;categories:WealthAssetType[];onNavigate:(tab:string)=>void}){
 const totals=new Map<string,number>();
 for(const row of dashboard?.assets??[])totals.set(row.assetType,(totals.get(row.assetType)??0)+(Number(row.value)||0));
 const total=Array.from(totals.values()).reduce((sum,value)=>sum+value,0);
 const steps=[{tab:"assets",title:assets.length?"Build your asset register":"Add your first asset",detail:"Choose a category and record a dated value.",icon:Landmark},{tab:"finance",title:"Understand income & debt",detail:"Record cash activity and outstanding loans.",icon:BookOpen},{tab:"goals",title:"Give your progress a purpose",detail:"Set a target with a date you can review.",icon:Target},{tab:"vault",title:"Keep the evidence safe",detail:"Store statements and supporting documents.",icon:ShieldCheck}];
 return <section aria-label="Your wealth roadmap" className="grid gap-4 lg:grid-cols-[1.4fr_1fr]">
  <Card className="border-orange-200 bg-gradient-to-br from-orange-50 via-white to-white"><CardHeader><CardTitle>{assets.length?"Make your wealth picture more useful":"Start small. See the bigger picture."}</CardTitle><CardDescription>{assets.length?"Keep the value, cash flow and evidence behind each asset together.":"Start with savings, land, a pension or anything else you own."}</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{steps.map(step=><button key={step.tab} onClick={()=>onNavigate(step.tab)} className="rounded-xl border bg-white p-4 text-left transition hover:border-orange-400 focus-visible:outline-2 focus-visible:outline-orange-500"><step.icon className="mb-2 size-5 text-orange-600"/><span className="flex items-center justify-between gap-2 font-semibold">{step.title}<ArrowRight className="size-4 shrink-0"/></span><span className="mt-1 block text-sm text-muted-foreground">{step.detail}</span></button>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>Your wealth mix</CardTitle><CardDescription>{total>0?`Asset values in ${dashboard?.summary?.currency??"KES"}. Allocation, not investment advice.`:"Your categories appear as you add and value assets."}</CardDescription></CardHeader><CardContent className="space-y-4">{Array.from(totals.entries()).sort((a,b)=>b[1]-a[1]).map(([code,value])=>{const share=total>0?value/total*100:0;return <div key={code}><div className="mb-1 flex flex-wrap justify-between gap-2 text-sm"><span>{categories.find(type=>type.code===code)?.label??code.replaceAll("_"," ")}</span><span>{money(value,dashboard?.summary?.currency)} · {share.toFixed(1)}%</span></div><div role="meter" aria-label={`${code.replaceAll("_"," ")} allocation`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={share} className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange-500" style={{width:`${Math.max(0,Math.min(100,share))}%`}}/></div></div>})}{!totals.size&&<div className="flex flex-wrap gap-2">{categories.slice(0,8).map(category=><button key={category.code} className="rounded-full border px-3 py-2 text-sm hover:bg-orange-50" onClick={()=>onNavigate("assets")}>{category.label}</button>)}</div>}<p className="text-xs text-muted-foreground">Cash flows cover the last 12 months. Asset valuations are not available cash.</p></CardContent></Card>
 </section>;
}

export function WealthLedgerPanel({asset,revision,busy,run}:{asset:WealthAsset;revision:number;busy:boolean;run:Run}){
 const [ledger,setLedger]=useState<WealthLedger|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);const can=useWealthAccess();
 useEffect(()=>{let current=true;setLedger(null);setError(false);wealthService.ledger(asset.id).then(response=>{if(current){const data=envelopeItem<WealthLedger|null>(response,null);setLedger(data);setError(!data);}}).catch(()=>{if(current)setError(true);});return()=>{current=false;};},[asset.id,revision,retry]);
 if(error)return <div role="alert" className="rounded-xl border p-4">Asset history could not be loaded. <Button variant="outline" onClick={()=>setRetry(value=>value+1)}>Retry history</Button></div>;
 if(!ledger)return <p role="status">Loading asset history…</p>;
 return <div className="grid gap-5 lg:grid-cols-2">
  <Card><CardHeader><CardTitle>Valuation history</CardTitle><CardDescription>{asset.name} · {asset.currency}. Older entries do not replace a newer value.</CardDescription></CardHeader><CardContent className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Date</th><th>Value</th><th>Source</th></tr></thead><tbody>{(ledger.valuations??[]).map(row=><tr className="border-t" key={row.id}><td className="py-3">{row.valuationDate}</td><td>{money(row.amount,asset.currency)}</td><td>{row.source.replaceAll("_"," ")}{row.notes&&<p className="text-xs text-muted-foreground">{row.notes}</p>}</td></tr>)}</tbody></table>{!ledger.valuations?.length&&<p className="py-4 text-sm">No valuation entries yet.</p>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Recorded cash activity</CardTitle><CardDescription>All recorded dates in {asset.currency}. Archive mistakes and record a corrected entry.</CardDescription></CardHeader><CardContent className="max-h-96 space-y-3 overflow-auto">{(ledger.cashFlows??[]).map(row=><div className="flex flex-wrap justify-between gap-3 rounded-xl border p-3" key={row.id}><div><strong>{row.flowType==="INCOME"?"Income":"Expense"} · {money(row.amount,asset.currency)}</strong><p className="text-sm text-muted-foreground">{row.category.replaceAll("_"," ")} · {row.entryDate}</p>{row.description&&<p className="text-sm">{row.description}</p>}</div>{can("finance")&&<Button disabled={busy} variant="ghost" onClick={()=>confirm("Archive this cash entry? Totals will be recalculated.")&&run(()=>wealthService.archiveCashFlow(row.id),"Cash entry archived.")}>Archive entry</Button>}</div>)}{!ledger.cashFlows?.length&&<p className="text-sm">No cash entries yet.</p>}</CardContent></Card>
  <Card className="lg:col-span-2"><CardHeader><CardTitle>Your debt register</CardTitle><CardDescription>Update balances as you repay. Monthly payments reduce projected cash flow; this does not make a bank payment.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">{(ledger.liabilities??[]).map(debt=><DebtBalance key={`${debt.id}-${revision}`} debt={debt} busy={busy||!can("finance")} run={run}/>)}{!ledger.liabilities?.length&&<p className="text-sm">No liabilities recorded for this asset.</p>}</CardContent></Card>
 </div>;
}

function DebtBalance({debt,busy,run}:{debt:WealthLiability;busy:boolean;run:Run}){
 const [balance,setBalance]=useState(debt.outstandingPrincipal),[monthly,setMonthly]=useState(debt.monthlyPayment??0);
 return <form className="space-y-3 rounded-xl border p-4" onSubmit={event=>{event.preventDefault();void run(()=>wealthService.updateLiabilityBalance(debt.id,{outstandingPrincipal:balance,monthlyPayment:monthly,maturityDate:debt.maturityDate}),"Debt balance updated.");}}><strong>{debt.lender} · {debt.currency}</strong><p className="text-sm text-muted-foreground">Original principal: {money(debt.originalPrincipal,debt.currency)}</p><label className="block text-sm">Outstanding balance<Input aria-label={`Outstanding balance for ${debt.lender}`} required disabled={busy} type="number" min={0} max={debt.originalPrincipal} step="any" value={balance} onChange={event=>setBalance(Number(event.target.value))}/></label><label className="block text-sm">Monthly payment<Input aria-label={`Monthly payment for ${debt.lender}`} disabled={busy} type="number" min={0} step="any" value={monthly} onChange={event=>setMonthly(Number(event.target.value))}/></label><div className="flex flex-wrap gap-2"><Button disabled={busy}>Update balance</Button><Button type="button" disabled={busy} variant="outline" onClick={()=>confirm("Archive this liability? It will no longer reduce net worth. Use a zero balance to retain a repaid loan.")&&run(()=>wealthService.archiveLiability(debt.id),"Liability archived.")}>Archive liability</Button></div></form>;
}
