"use client";
import {FormEvent,useEffect,useState} from "react";
import {API} from "@/lib/api";
import {apiErrorMessage} from "@/lib/api-error";
import {Button} from "@/components/ui/button";
import {envelopeItem} from "@/lib/api-envelope";
type Policy={commissionRate:number;eligiblePaymentCount:number;minimumPayout:number;holdDays:number;version:number};
const numberValue=(value:unknown)=>Number.isFinite(Number(value))?Number(value):null;
function policyValue(value:unknown):Policy|null{
 if(!value||typeof value!=="object"||Array.isArray(value))return null;
 const source=value as Record<string,unknown>;
 const commissionRate=numberValue(source.commissionRate),eligiblePaymentCount=numberValue(source.eligiblePaymentCount),minimumPayout=numberValue(source.minimumPayout),holdDays=numberValue(source.holdDays),version=numberValue(source.version);
 return commissionRate===null||eligiblePaymentCount===null||minimumPayout===null||holdDays===null||version===null?null:{commissionRate,eligiblePaymentCount,minimumPayout,holdDays,version};
}
export default function AffiliatePolicy(){
 const [policy,setPolicy]=useState<Policy|null>(null),[draft,setDraft]=useState<Policy|null>(null),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 async function load(){setBusy(true);setError(null);try{const r=await API.get("/affiliate/admin/policy");const next=policyValue(envelopeItem<unknown|null>(r,null));if(!next)throw new Error("Affiliate policy response was empty or invalid");setPolicy(next);setDraft(null)}catch(e){setPolicy(null);setError(apiErrorMessage(e,"Affiliate policy could not be loaded."))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setError(null);try{const r=await API.put("/affiliate/admin/policy",{...draft,reason:reason.trim()});const next=policyValue(envelopeItem<unknown|null>(r,null));if(!next)throw new Error("Affiliate policy response was empty or invalid");setPolicy(next);setDraft(null);setReason("")}catch(e){setError(apiErrorMessage(e,"Policy could not be saved. Reload if another administrator changed it."))}finally{setBusy(false)}}
 const fields:([keyof Omit<Policy,"version">,string,number,number,string])[]=[["commissionRate","Default commission (%)",0.01,100,"0.01"],["eligiblePaymentCount","Eligible subscription payments per referred user",1,100,"1"],["minimumPayout","Default minimum payout (KES)",0.01,9999999999999,"0.01"],["holdDays","Commission hold (days)",0,365,"1"]];
 return <section id="affiliate-policy" className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Affiliate reward policy</h2><p className="text-sm text-slate-600">Superadmin controls the programme defaults. Default rate and minimum apply to new affiliate profiles; existing overrides are managed in the directory. Payment count and hold apply to future qualifying payments. Earned commissions and existing payout requests are not recalculated.</p>{error&&<div role="alert">{error}<Button variant="outline" disabled={busy} onClick={()=>void load()}>Reload policy</Button></div>}{!policy?<p>{busy?"Loading policy…":"Policy unavailable."}</p>:draft?<form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label,min,max,step])=><label key={key} className="space-y-2 text-sm">{label}<input className="block w-full rounded border p-2" aria-label={label} type="number" required min={min} max={max} step={step} disabled={busy} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div><p>Preview: {draft.commissionRate}% on up to {draft.eligiblePaymentCount} qualifying subscription payments, released after {draft.holdDays} days. Default minimum payout: KES {draft.minimumPayout.toLocaleString()}.</p><label className="block text-sm">Reason for policy change<textarea aria-label="Reason for policy change" required maxLength={1000} disabled={busy} className="mt-2 block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex gap-3"><Button type="button" variant="outline" disabled={busy} onClick={()=>setDraft(null)}>Cancel policy edit</Button><Button disabled={busy||!reason.trim()}>Publish affiliate policy</Button></div></form>:<><dl className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><div key={key}><dt className="text-sm text-slate-500">{label}</dt><dd className="font-semibold">{policy[key]}</dd></div>)}</dl><Button disabled={busy} onClick={()=>{setDraft({...policy});setReason("")}}>Edit reward policy</Button></>}</section>;
}
