"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { estateService } from "@/services/business-workflows.service";
import { EstateServiceCharge, PropertyOwnership } from "@/types/business-workflows";
import Link from "next/link";
import { useAuthStore } from "@/store/authStore";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { apiErrorMessage } from "@/lib/api-error";
import { EstateOperationsPanel } from "@/components/estate/EstateOperationsPanel";

export default function EstatePage(){
 const permissions=useAuthStore(s=>s.permissions); const canManage=permissions.includes("manage_estate");
 const scopedPropertyIds=useAuthStore(s=>s.propertyIds);
 const [items,setItems]=useState<PropertyOwnership[]>([]); const [busy,setBusy]=useState(false);
 const [charges,setCharges]=useState<EstateServiceCharge[]>([]); const canCharge=permissions.includes("create_service_charge");
 const [propertyId,setPropertyId]=useState(""); const [unitId,setUnitId]=useState(""); const [homeownerUserId,setHomeownerUserId]=useState("");
 const [ownershipStart,setOwnershipStart]=useState(new Date().toISOString().slice(0,10));
 const [endingOwnership,setEndingOwnership]=useState<PropertyOwnership|null>(null); const [endDate,setEndDate]=useState(new Date().toISOString().slice(0,10)); const [endReason,setEndReason]=useState("");
 const [chargeOwnershipId,setChargeOwnershipId]=useState(""),[chargeAmount,setChargeAmount]=useState(""),[chargeCurrency,setChargeCurrency]=useState("KES"),[chargeDue,setChargeDue]=useState(new Date().toISOString().slice(0,10)),[chargeDescription,setChargeDescription]=useState("Service charge");
 const load=useCallback(async()=>{try{const [o,c]=await Promise.all([estateService.listOwnership(),estateService.listServiceCharges()]);setItems(o.data?.data??[]);setCharges(c.data?.data??[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Could not load estate records."))}},[]);
 useEffect(()=>{load()},[load]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);try{await estateService.createOwnership({propertyId:Number(propertyId),unitId:unitId?Number(unitId):undefined,homeownerUserId:Number(homeownerUserId),ownershipStart,source:"ESTATE_ONBOARDING"});toast.success("Homeowner added with ownership history.");setUnitId("");setHomeownerUserId("");await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not add homeowner."))}finally{setBusy(false)}}
 async function end(e:FormEvent){e.preventDefault();if(!endingOwnership)return;setBusy(true);try{await estateService.endOwnership(endingOwnership.id,{endDate,reason:endReason.trim()});toast.success("Ownership ended, the homeowner was notified, and history was retained.");setEndingOwnership(null);setEndReason("");await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not end ownership."))}finally{setBusy(false)}}
 async function createCharge(e:FormEvent){e.preventDefault();setBusy(true);try{await estateService.createServiceCharge({ownershipId:Number(chargeOwnershipId),amount:Number(chargeAmount),currency:chargeCurrency,dueDate:chargeDue,description:chargeDescription});toast.success("Service-charge invoice created and sent.");setChargeAmount("");await load()}catch(err:unknown){toast.error(apiErrorMessage(err,"Could not create service charge."))}finally{setBusy(false)}}
 const overdue=charges.filter(charge=>charge.status==="OVERDUE"); const outstanding=charges.filter(charge=>!charge.paid).reduce((sum,charge)=>sum+charge.pendingAmount,0);
 const estatePropertyIds=Array.from(new Set([...items.filter(item=>item.active).map(item=>item.propertyId),...(canManage?scopedPropertyIds:[])]));
 return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#EF4217]">SlickHood Estates</p><h1 className="mt-1 text-3xl font-bold">{canManage?"Estate Management":"My Home"}</h1><p className="text-muted-foreground">{canManage?"Manage homeowners, current ownership, preserved ownership history, service charges and estate operations.":"View your ownership history, service charges, balances and payment documents."}</p></div>
 {!canManage&&<div className="grid gap-4 sm:grid-cols-3"><Card><CardHeader className="pb-2"><CardDescription>Owned units</CardDescription><CardTitle>{items.filter(item=>item.active).length}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Outstanding balance</CardDescription><CardTitle>{charges[0]?.currency??"KES"} {outstanding.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Overdue charges</CardDescription><CardTitle className={overdue.length?"text-red-600":"text-emerald-600"}>{overdue.length}</CardTitle></CardHeader></Card></div>}
 {canManage&&<Card><CardHeader><CardTitle>Add homeowner</CardTitle><CardDescription>Link the homeowner to a property or unit. A previous active unit owner is closed automatically, never deleted.</CardDescription></CardHeader><CardContent><form onSubmit={create} className="grid gap-4 md:grid-cols-4">
  <div><Label>Property ID</Label><Input required type="number" min="1" value={propertyId} onChange={e=>setPropertyId(e.target.value)}/></div>
  <div><Label>Unit ID (optional)</Label><Input type="number" min="1" value={unitId} onChange={e=>setUnitId(e.target.value)}/></div>
  <div><Label>Homeowner user ID</Label><Input required type="number" min="1" value={homeownerUserId} onChange={e=>setHomeownerUserId(e.target.value)}/></div>
  <div><Label>Ownership start</Label><Input required type="date" value={ownershipStart} onChange={e=>setOwnershipStart(e.target.value)}/></div>
  <div className="md:col-span-4"><Button disabled={busy} className="bg-[#EF4217]">Add homeowner</Button></div></form></CardContent></Card>}
 <Card><CardHeader><CardTitle>Ownership records</CardTitle></CardHeader><CardContent className="space-y-3">{items.length===0&&<p className="py-8 text-center text-muted-foreground">No ownership records for this active role.</p>}{items.map(item=><div key={item.id} className="flex flex-col justify-between gap-3 rounded-lg border p-4 sm:flex-row sm:items-center"><div><div className="flex gap-2"><strong>Homeowner #{item.homeownerUserId}</strong><Badge variant={item.active?"default":"outline"}>{item.active?"Current":"Historical"}</Badge></div><p className="text-sm text-muted-foreground">Property {item.propertyId}{item.unitId?` · Unit ${item.unitId}`:""} · {item.ownershipStart}{item.ownershipEnd?` to ${item.ownershipEnd}`:" to present"}</p>{item.terminationReason&&<p className="mt-1 text-sm text-muted-foreground">Reason: {item.terminationReason}</p>}</div>{canManage&&item.active&&<Button size="sm" variant="outline" onClick={()=>{setEndingOwnership(item);setEndDate(new Date().toISOString().slice(0,10))}}>End ownership</Button>}</div>)}</CardContent></Card>
 {canCharge&&<Card><CardHeader><CardTitle>Create service charge</CardTitle><CardDescription>This creates a real invoice routed to the property owner&apos;s approved payment account.</CardDescription></CardHeader><CardContent><form onSubmit={createCharge} className="grid gap-4 md:grid-cols-5"><div><Label>Ownership ID</Label><Input required type="number" min="1" value={chargeOwnershipId} onChange={e=>setChargeOwnershipId(e.target.value)}/></div><div><Label>Amount</Label><Input required type="number" min="0.01" step="0.01" value={chargeAmount} onChange={e=>setChargeAmount(e.target.value)}/></div><div><Label>Currency</Label><Input value={chargeCurrency} onChange={e=>setChargeCurrency(e.target.value.toUpperCase())}/></div><div><Label>Due date</Label><Input required type="date" value={chargeDue} onChange={e=>setChargeDue(e.target.value)}/></div><div><Label>Description</Label><Input required value={chargeDescription} onChange={e=>setChargeDescription(e.target.value)}/></div><div className="md:col-span-5"><Button disabled={busy}>Create invoice</Button></div></form></CardContent></Card>}
 <Card><CardHeader><CardTitle>Service charges</CardTitle><CardDescription>Balances update after verified payment reconciliation. Checkout and receipts are available in Invoices.</CardDescription></CardHeader><CardContent className="space-y-3">{charges.length===0&&<p className="py-6 text-center text-muted-foreground">No service charges for this role.</p>}{charges.map(c=><div key={c.id} className="flex flex-col justify-between gap-3 rounded border p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong>{c.currency} {c.pendingAmount.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} {c.paid?"paid":"outstanding"}</strong><Badge variant={c.status==="PAID"?"default":"outline"} className={c.status==="OVERDUE"?"border-red-200 bg-red-50 text-red-700":c.status==="PAID"?"bg-emerald-600":""}>{c.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{c.description} · {c.propertyName} / {c.unitRef} · Due {c.dueDate} · {c.invoiceRef}</p></div><Button asChild size="sm" variant="outline"><Link href="/dashboard/invoices">View invoice</Link></Button></div>)}</CardContent></Card>
 <EstateOperationsPanel propertyIds={estatePropertyIds} canManage={canManage}/>
 <Dialog open={Boolean(endingOwnership)} onOpenChange={open=>{if(!open&&!busy){setEndingOwnership(null);setEndReason("")}}}><DialogContent><form onSubmit={end} className="space-y-4"><DialogHeader><DialogTitle>End ownership</DialogTitle><DialogDescription>This removes current homeowner access but preserves ownership and financial history. The homeowner will receive a notification.</DialogDescription></DialogHeader><div><Label htmlFor="ownership-end-date">End date</Label><Input id="ownership-end-date" required type="date" max={new Date().toISOString().slice(0,10)} value={endDate} onChange={e=>setEndDate(e.target.value)}/></div><div><Label htmlFor="ownership-end-reason">Reason</Label><Textarea id="ownership-end-reason" required maxLength={500} value={endReason} onChange={e=>setEndReason(e.target.value)} placeholder="For example: property sale completed"/></div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={()=>setEndingOwnership(null)}>Cancel</Button><Button type="submit" variant="destructive" disabled={busy||!endReason.trim()}>End ownership</Button></DialogFooter></form></DialogContent></Dialog>
 </div>
}
