"use client";
import {useCallback,useEffect,useState} from "react";import {RefreshCw,ShieldCheck,Store,PackageSearch} from "lucide-react";import {toast} from "sonner";
import {moderateSokoProduct,moderateSokoStore,sokoAdminProducts,sokoAdminStores,sokoAdminSummary,SokoProduct,SokoStore} from "@/services/soko";import {apiErrorMessage} from "@/lib/api-error";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";import {Button} from "@/components/ui/button";import {Badge} from "@/components/ui/badge";import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";import {Textarea} from "@/components/ui/textarea";
type Summary={stores:number;pendingStores:number;publishedStores:number;products:number;publishedProducts:number;orders:number;activeOrders:number};type Action={target:"store"|"product";id:number;name:string;decision:"APPROVE"|"REJECT"|"SUSPEND"|"REACTIVATE"};
export default function SokoManagement(){const [summary,setSummary]=useState<Summary|null>(null),[stores,setStores]=useState<SokoStore[]>([]),[products,setProducts]=useState<SokoProduct[]>([]),[busy,setBusy]=useState(false),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{const [s,st,p]=await Promise.all([sokoAdminSummary(),sokoAdminStores(),sokoAdminProducts()]);setSummary(s.data?.data??null);setStores(Array.isArray(st.data?.data)?st.data.data:[]);setProducts(Array.isArray(p.data?.data)?p.data.data:[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Soko administration could not be loaded."))}finally{setBusy(false)}},[]);useEffect(()=>{void load()},[load]);
 function open(next:Action){setAction(next);setReason("")}
 async function decide(){if(!action)return;if(["REJECT","SUSPEND"].includes(action.decision)&&!reason.trim()){toast.error("A clear reason is required.");return}setBusy(true);try{if(action.target==="store")await moderateSokoStore(action.id,action.decision,reason.trim()||undefined);else await moderateSokoProduct(action.id,action.decision as "SUSPEND"|"REACTIVATE",reason.trim()||undefined);toast.success(`${action.name} updated.`);setAction(null);await load()}catch(e:unknown){toast.error(apiErrorMessage(e,"Moderation decision could not be saved."))}finally{setBusy(false)}}
 return <div className="space-y-6 px-3 py-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#FF4B1F]">Marketplace trust & safety</p><h1 className="mt-1 text-3xl font-bold text-[#162B63]">Soko administration</h1><p className="text-slate-500">Review shops, intervene on unsafe listings and monitor marketplace operations.</p></div><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw className={`mr-2 size-4 ${busy?"animate-spin":""}`}/>Refresh</Button></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Stores",summary?.stores],["Awaiting review",summary?.pendingStores],["Products",summary?.products],["Active orders",summary?.activeOrders]].map(([label,value])=><Card key={String(label)}><CardContent className="pt-5"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-[#162B63]">{Number(value??0).toLocaleString()}</p></CardContent></Card>)}</div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Store className="size-5 text-[#FF4B1F]"/>Shop review queue</CardTitle><CardDescription>Merchant payment destinations must already be verified. Approval makes the shop discoverable; suspension removes it immediately without deleting records.</CardDescription></CardHeader><CardContent className="space-y-3">{stores.map(store=><div key={store.id} className="flex flex-col justify-between gap-4 rounded-xl border p-4 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{store.name}</b><Badge variant="outline">{store.status.replaceAll("_"," ")}</Badge></div><p className="mt-1 text-sm text-slate-500">Owner #{store.ownerUserId} · {store.address||"No address"} · {store.pickupEnabled?"Pickup":""}{store.pickupEnabled&&store.deliveryEnabled?" + ":""}{store.deliveryEnabled?"Delivery":""}</p>{store.reviewReason&&<p className="mt-1 text-sm text-red-700">Last decision: {store.reviewReason}</p>}</div><div className="flex flex-wrap gap-2">{store.status==="PENDING_REVIEW"&&<><Button onClick={()=>open({target:"store",id:store.id,name:store.name,decision:"REJECT"})} variant="destructive">Reject</Button><Button onClick={()=>open({target:"store",id:store.id,name:store.name,decision:"APPROVE"})} className="bg-emerald-600">Approve</Button></>}{store.status==="PUBLISHED"&&<Button onClick={()=>open({target:"store",id:store.id,name:store.name,decision:"SUSPEND"})} variant="destructive">Suspend</Button>}{store.status==="SUSPENDED"&&<Button onClick={()=>open({target:"store",id:store.id,name:store.name,decision:"REACTIVATE"})}>Reactivate</Button>}</div></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageSearch className="size-5 text-blue-600"/>Product intervention</CardTitle><CardDescription>Products normally publish under an approved shop. Superadmin can remove a problematic listing while preserving audit history.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{products.map(product=><div key={product.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><b>{product.name}</b><p className="text-sm text-slate-500">Store #{product.storeId} · {product.category} · stock {product.stockQuantity}</p></div><Badge variant="outline">{product.status}</Badge></div>{product.moderationReason&&<p className="mt-2 text-xs text-red-700">{product.moderationReason}</p>}<div className="mt-3">{["PUBLISHED","OUT_OF_STOCK"].includes(product.status)&&<Button size="sm" variant="destructive" onClick={()=>open({target:"product",id:product.id,name:product.name,decision:"SUSPEND"})}>Suspend listing</Button>}{product.status==="SUSPENDED"&&<Button size="sm" onClick={()=>open({target:"product",id:product.id,name:product.name,decision:"REACTIVATE"})}>Restore listing</Button>}</div></div>)}</CardContent></Card>
 <Dialog open={!!action} onOpenChange={openState=>!openState&&setAction(null)}><DialogContent><DialogHeader><DialogTitle>{action?.decision} {action?.name}</DialogTitle><DialogDescription>This decision is recorded against the Superadmin account. Rejections and suspensions require a useful reason.</DialogDescription></DialogHeader>{["REJECT","SUSPEND"].includes(action?.decision??"")&&<Textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the policy or verification issue clearly."/>}<DialogFooter><Button variant="outline" onClick={()=>setAction(null)}>Cancel</Button><Button disabled={busy} onClick={()=>void decide()} variant={["REJECT","SUSPEND"].includes(action?.decision??"")?"destructive":"default"}><ShieldCheck className="mr-2 size-4"/>Confirm decision</Button></DialogFooter></DialogContent></Dialog></div>}
