"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight,Building2,Car,FileCheck2,Flame,HeartPulse,House,Plane,RefreshCw,ShieldCheck,Ship,Users,Upload,Plus,AlertCircle} from "lucide-react";
import {insuranceService,InsuranceCase,InsuranceClaim,InsuranceCompany,InsuranceDocument,InsurancePolicy,InsuranceProduct} from "@/services/insurance.service";
import {apiErrorMessage} from "@/lib/api-error";
import {toast} from "sonner";
import {useAuthStore} from "@/store/authStore";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Textarea} from "@/components/ui/textarea";import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";import {Badge} from "@/components/ui/badge";

const icons:Record<string,typeof Car>={MOTOR:Car,DOMESTIC:House,FIRE_ALLIED:Flame,WIBA_EL:Users,ALL_RISKS:ShieldCheck,MEDICAL:HeartPulse,MARINE_CARGO:Ship,TRAVEL:Plane};
const tones=["bg-sky-50 text-sky-700","bg-emerald-50 text-emerald-700","bg-orange-50 text-orange-700","bg-violet-50 text-violet-700","bg-indigo-50 text-indigo-700","bg-rose-50 text-rose-700","bg-cyan-50 text-cyan-700","bg-amber-50 text-amber-700"];
const money=(n:number|undefined,c="KES")=>n==null?"—":new Intl.NumberFormat("en-KE",{style:"currency",currency:c,maximumFractionDigits:2}).format(n);
const title=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase());
const tone=(s:string)=>s.includes("REJECT")||s==="DECLINED"||s==="LAPSED"?"destructive":s.includes("ISSUED")||s==="ACTIVE"||s==="VERIFIED"||s==="RENEWED"?"default":"secondary";

export default function InsuranceHubPage(){
 const permissions=useAuthStore(s=>s.permissions),canOperate=permissions.some(p=>["review_insurance_applications","manage_insurance_quotes","manage_insurance_claims","manage_insurance_renewals"].includes(p));
 const [products,setProducts]=useState<InsuranceProduct[]>([]),[companies,setCompanies]=useState<InsuranceCompany[]>([]),[cases,setCases]=useState<InsuranceCase[]>([]),[policies,setPolicies]=useState<InsurancePolicy[]>([]),[claims,setClaims]=useState<InsuranceClaim[]>([]),[documents,setDocuments]=useState<InsuranceDocument[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [quoteOpen,setQuoteOpen]=useState(false),[claimOpen,setClaimOpen]=useState(false),[documentOpen,setDocumentOpen]=useState(false),[selectedProduct,setSelectedProduct]=useState<InsuranceProduct|null>(null);
 const [quoteForm,setQuoteForm]=useState({fullName:"",email:"",phone:"",subjectType:"",subjectDescription:"",sumInsured:"",currency:"KES",coverStartDate:"",riskDetails:"",consent:false});
 const [claimForm,setClaimForm]=useState({policyId:"",incidentAt:"",incidentLocation:"",description:"",estimatedAmount:""});
 const [documentForm,setDocumentForm]=useState({parent:"",category:"PROPOSAL",file:null as File|null});
 const load=useCallback(async()=>{setLoading(true);try{const [p,co,ca,po,cl,d]=await Promise.all([insuranceService.products(),insuranceService.companies(),insuranceService.cases(),insuranceService.policies(),insuranceService.claims(),insuranceService.documents()]);setProducts(Array.isArray(p)?p:[]);setCompanies(Array.isArray(co.data?.data)?co.data.data:[]);setCases(Array.isArray(ca)?ca:[]);setPolicies(Array.isArray(po)?po:[]);setClaims(Array.isArray(cl)?cl:[]);setDocuments(Array.isArray(d)?d:[])}catch(e:unknown){toast.error(apiErrorMessage(e,"Could not load your insurance workspace."))}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const quotes=useMemo(()=>cases.flatMap(c=>c.quotes.filter(q=>["PUBLISHED","SELECTED"].includes(q.status)).map(q=>({c,q}))),[cases]);
 const openQuote=(p:InsuranceProduct)=>{setSelectedProduct(p);setQuoteForm(v=>({...v,subjectType:p.subjectTypes[0]??"PERSON"}));setQuoteOpen(true)};
 async function submitQuote(e:FormEvent){e.preventDefault();if(!selectedProduct)return;setBusy(true);try{await insuranceService.createCase({...quoteForm,productCode:selectedProduct.code,sumInsured:quoteForm.sumInsured?Number(quoteForm.sumInsured):null,coverStartDate:quoteForm.coverStartDate||null});toast.success("Quote request submitted to Silverwood.");setQuoteOpen(false);await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not submit the request."))}finally{setBusy(false)}}
 async function choose(caseId:number,quoteId:number){setBusy(true);try{await insuranceService.selectQuote(caseId,quoteId);toast.success("Quote selected. Record payment after paying the insurer.");await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not select the quote."))}finally{setBusy(false)}}
 async function payment(c:InsuranceCase){const q=c.quotes.find(x=>x.id===c.selectedQuoteId),reference=window.prompt("Enter the insurer or bank payment reference");if(!q||!reference)return;setBusy(true);try{await insuranceService.recordPayment(c.id,{amount:q.totalPremium,currency:q.currency,paymentReference:reference,paidAt:new Date().toISOString().slice(0,19)});toast.success("Payment recorded. Please upload its proof.");await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not record payment."))}finally{setBusy(false)}}
 async function proof(id:number,file:File){setBusy(true);try{await insuranceService.uploadPaymentProof(id,file);toast.success("Payment proof uploaded securely.");await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not upload proof."))}finally{setBusy(false)}}
 async function submitClaim(e:FormEvent){e.preventDefault();setBusy(true);try{await insuranceService.createClaim({...claimForm,policyId:Number(claimForm.policyId),incidentAt:new Date(claimForm.incidentAt).toISOString().slice(0,19),estimatedAmount:claimForm.estimatedAmount?Number(claimForm.estimatedAmount):null});toast.success("Claim submitted to Silverwood.");setClaimOpen(false);await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not submit claim."))}finally{setBusy(false)}}
 async function submitDocument(e:FormEvent){e.preventDefault();if(!documentForm.file||!documentForm.parent)return;const [kind,id]=documentForm.parent.split(":");const parent=kind==="case"?{caseId:Number(id)}:kind==="policy"?{policyId:Number(id)}:{claimId:Number(id)};setBusy(true);try{await insuranceService.uploadDocument({...parent,category:documentForm.category,file:documentForm.file});toast.success("Document uploaded securely.");setDocumentOpen(false);await load()}catch(x:unknown){toast.error(apiErrorMessage(x,"Could not upload document."))}finally{setBusy(false)}}
 return <div className="min-h-screen bg-[#f5f8fc] p-3 text-[#10243e] sm:p-6">
  <section className="overflow-hidden rounded-3xl bg-[#0c2d57] px-5 py-8 text-white shadow-xl sm:px-10 lg:px-14"><div className="grid items-center gap-10 lg:grid-cols-[1.4fr_.8fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.28em] text-[#7db8ea]">Silverwood Insurance Agency</p><h1 className="max-w-3xl text-4xl font-bold sm:text-5xl">Insurance protection, made clear and connected.</h1><p className="mt-4 max-w-2xl text-lg text-white/75">Request advice, compare quotations, manage policies, claims and renewals in one secure place.</p><div className="mt-7 flex gap-3"><Button className="bg-[#1769aa]" onClick={()=>products[0]&&openQuote(products[0])}>Get a Quote <ArrowRight className="ml-2 size-4"/></Button><Button variant="outline" className="border-white/30 bg-white/5 text-white" onClick={()=>document.getElementById("insurance-workspace")?.scrollIntoView({behavior:"smooth"})}>My Insurance</Button></div></div><div className="rounded-3xl border border-white/15 bg-white/10 p-6"><ShieldCheck className="size-12 text-[#7db8ea]"/><h2 className="mt-5 text-2xl font-semibold">Human advice. Digital convenience.</h2><p className="mt-2 text-white/70">Silverwood advisers review each request. You choose the quote; payment verification and policy issuance remain controlled.</p></div></div></section>
  <section className="py-10"><p className="text-sm font-semibold text-[#1769aa]">Insurance products</p><h2 className="text-2xl font-bold">What would you like to protect?</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{products.map((p,i)=>{const Icon=icons[p.code]??ShieldCheck;return <Card key={p.code} className="group border-0 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="p-5"><div className={`flex size-12 items-center justify-center rounded-2xl ${tones[i%tones.length]}`}><Icon className="size-6"/></div><h3 className="mt-4 font-bold">{p.name}</h3><p className="mt-2 min-h-10 text-sm text-muted-foreground">{p.description}</p><Button variant="link" className="h-auto p-0 text-[#1769aa]" onClick={()=>openQuote(p)}>Request a quote <ArrowRight className="ml-1 size-4"/></Button></CardContent></Card>})}</div></section>
  <section id="insurance-workspace" className="pb-10"><Tabs defaultValue="applications"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[#1769aa]">Your insurance workspace</p><h2 className="text-2xl font-bold">Applications, policies and support</h2></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setDocumentOpen(true)}><Upload className="mr-2 size-4"/>Upload document</Button><Button variant="ghost" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 size-4 ${loading?"animate-spin":""}`}/>Refresh</Button></div></div><TabsList className="mt-5 h-auto flex-wrap justify-start"><TabsTrigger value="applications">Applications ({cases.length})</TabsTrigger><TabsTrigger value="quotes">Quotes ({quotes.length})</TabsTrigger><TabsTrigger value="policies">Policies ({policies.length})</TabsTrigger><TabsTrigger value="claims">Claims ({claims.length})</TabsTrigger><TabsTrigger value="documents">Documents ({documents.length})</TabsTrigger></TabsList>
   <TabsContent value="applications" className="mt-4 space-y-3">{cases.map(c=><Card key={c.id}><CardContent className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:justify-between"><div><div className="flex gap-2"><h3 className="font-bold">{c.reference}</h3><Badge variant={tone(c.status)}>{title(c.status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{title(c.productCode)} · {c.subjectDescription}</p><p className="mt-2 text-sm">Requested cover: <strong>{money(c.sumInsured,c.currency)}</strong></p></div><div>{c.status==="CUSTOMER_SELECTED"&&<Button size="sm" onClick={()=>void payment(c)} disabled={busy}>Record payment</Button>}{c.payments.map(p=>!p.proofAvailable&&p.status==="PENDING_VERIFICATION"?<Label key={p.id} className="cursor-pointer"><span className="inline-flex h-9 items-center rounded-md border px-3 text-sm font-medium">Upload payment proof</span><Input className="sr-only" type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>e.target.files?.[0]&&void proof(p.id,e.target.files[0])}/></Label>:null)}</div></div>{c.payments[0]&&<div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">Payment: {money(c.payments[0].amount,c.payments[0].currency)} · <Badge variant={tone(c.payments[0].status)}>{title(c.payments[0].status)}</Badge></div>}</CardContent></Card>)}{!loading&&!cases.length&&<Empty text="No applications yet. Select a product above to request your first quote."/>}</TabsContent>
   <TabsContent value="quotes" className="mt-4 grid gap-4 lg:grid-cols-2">{quotes.map(({c,q})=><Card key={q.id} className={c.selectedQuoteId===q.id?"border-[#1769aa]":""}><CardHeader><div className="flex justify-between"><CardTitle>{q.companyName}</CardTitle><Badge variant={tone(q.status)}>{title(q.status)}</Badge></div><p className="text-sm text-muted-foreground">{c.reference} · valid to {q.validUntil}</p></CardHeader><CardContent><p className="text-2xl font-bold">{money(q.totalPremium,q.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Premium {money(q.basePremium,q.currency)} + levies {money(q.taxesLevies,q.currency)}</p><p className="mt-4 text-sm">{q.coverageSummary}</p>{q.excessDetails&&<p className="mt-2 text-sm"><strong>Excess:</strong> {q.excessDetails}</p>}{q.status==="PUBLISHED"&&<Button className="mt-4" onClick={()=>void choose(c.id,q.id)} disabled={busy}>Choose this quote</Button>}</CardContent></Card>)}{!quotes.length&&<Empty text="Adviser-prepared quotes will appear here for a clear comparison."/>}</TabsContent>
   <TabsContent value="policies" className="mt-4 space-y-3"><div className="flex justify-end"><Button onClick={()=>setClaimOpen(true)} disabled={!policies.length}><Plus className="mr-2 size-4"/>Start a claim</Button></div>{policies.map(p=><Card key={p.id}><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:justify-between"><div><h3 className="font-bold">{p.policyNumber}</h3><p className="text-sm text-muted-foreground">{p.companyName} · {title(p.productCode)}</p></div><div className="text-sm sm:text-right"><Badge variant={tone(p.status)}>{title(p.status)}</Badge><p className="mt-2">{p.startDate} to {p.endDate}</p><p>Renewal: {title(p.renewalStatus)}</p></div></CardContent></Card>)}{!policies.length&&<Empty text="Issued schedules and policies will be available here."/>}</TabsContent>
   <TabsContent value="claims" className="mt-4 space-y-3">{claims.map(c=><Card key={c.id}><CardContent className="p-5"><div className="flex justify-between"><h3 className="font-bold">{c.reference}</h3><Badge variant={tone(c.status)}>{title(c.status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Policy {c.policyNumber} · {new Date(c.incidentAt).toLocaleDateString("en-KE")}</p><p className="mt-3 text-sm">{c.description}</p>{c.resolutionNotes&&<p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm">{c.resolutionNotes}</p>}</CardContent></Card>)}{!claims.length&&<Empty text="Claims will be tracked here from acknowledgement to closure."/>}</TabsContent>
   <TabsContent value="documents" className="mt-4 grid gap-3 md:grid-cols-2">{documents.map(d=><a key={d.id} href={d.downloadUrl} target="_blank" rel="noreferrer"><Card className="hover:border-[#1769aa]"><CardContent className="flex items-center gap-3 p-4"><FileCheck2 className="size-7 text-[#1769aa]"/><div className="min-w-0"><p className="truncate font-medium">{d.displayName}</p><p className="text-xs text-muted-foreground">{title(d.category)} · v{d.versionNumber} · {(d.fileSize/1024).toFixed(0)} KB</p></div></CardContent></Card></a>)}{!documents.length&&<Empty text="Policy, claim and supporting documents are stored here securely."/>}</TabsContent>
  </Tabs></section>
  <section className="pb-10"><p className="text-sm font-semibold text-[#1769aa]">Insurance partners</p><h2 className="text-2xl font-bold">Companies coordinated by Silverwood</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{companies.map(c=><Card key={c.code} className="border-0 shadow-sm"><CardContent className="p-5"><div className="flex size-10 items-center justify-center rounded-xl bg-[#0c2d57] text-white"><Building2 className="size-5"/></div><h3 className="mt-4 font-bold">{c.name}</h3><p className="mt-1 text-xs text-muted-foreground">Quotes and premium processing coordinated by Silverwood.</p></CardContent></Card>)}</div></section>
  <div className="pb-8 text-center text-sm text-muted-foreground"><p>Insurance services are provided by Silverwood Insurance Agency.</p>{canOperate&&<Button asChild variant="outline" className="mt-3"><Link href="/dashboard/insurance/operations">Open Silverwood operations</Link></Button>}<div><Link href="/dashboard" className="font-semibold text-[#1769aa]">Back to SlickHood</Link></div></div>
  <QuoteDialog open={quoteOpen} setOpen={setQuoteOpen} product={selectedProduct} form={quoteForm} setForm={setQuoteForm} submit={submitQuote} busy={busy}/>
  <Dialog open={claimOpen} onOpenChange={setClaimOpen}><DialogContent><form onSubmit={submitClaim}><DialogHeader><DialogTitle>Start a claim</DialogTitle><DialogDescription>Report the incident promptly. Silverwood will guide you on evidence.</DialogDescription></DialogHeader><div className="mt-5 space-y-4"><Field label="Policy"><Select required value={claimForm.policyId} onValueChange={policyId=>setClaimForm({...claimForm,policyId})}><SelectTrigger><SelectValue placeholder="Select policy"/></SelectTrigger><SelectContent>{policies.filter(p=>p.status==="ACTIVE").map(p=><SelectItem key={p.id} value={String(p.id)}>{p.policyNumber} · {p.companyName}</SelectItem>)}</SelectContent></Select></Field><Field label="Incident date and time"><Input required type="datetime-local" max={new Date().toISOString().slice(0,16)} value={claimForm.incidentAt} onChange={e=>setClaimForm({...claimForm,incidentAt:e.target.value})}/></Field><Field label="Location (optional)"><Input maxLength={300} value={claimForm.incidentLocation} onChange={e=>setClaimForm({...claimForm,incidentLocation:e.target.value})}/></Field><Field label="What happened?"><Textarea required maxLength={12000} value={claimForm.description} onChange={e=>setClaimForm({...claimForm,description:e.target.value})}/></Field><Field label="Estimated loss (optional)"><Input type="number" min="0" step="0.01" value={claimForm.estimatedAmount} onChange={e=>setClaimForm({...claimForm,estimatedAmount:e.target.value})}/></Field></div><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={()=>setClaimOpen(false)}>Cancel</Button><Button disabled={busy}>Submit claim</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={documentOpen} onOpenChange={setDocumentOpen}><DialogContent><form onSubmit={submitDocument}><DialogHeader><DialogTitle>Upload insurance document</DialogTitle><DialogDescription>PDF, JPG or PNG, up to 10 MB. Downloads expire.</DialogDescription></DialogHeader><div className="mt-5 space-y-4"><Field label="Attach to"><Select required value={documentForm.parent} onValueChange={parent=>setDocumentForm({...documentForm,parent})}><SelectTrigger><SelectValue placeholder="Choose a record"/></SelectTrigger><SelectContent>{cases.map(c=><SelectItem key={`case:${c.id}`} value={`case:${c.id}`}>Application · {c.reference}</SelectItem>)}{policies.map(p=><SelectItem key={`policy:${p.id}`} value={`policy:${p.id}`}>Policy · {p.policyNumber}</SelectItem>)}{claims.map(c=><SelectItem key={`claim:${c.id}`} value={`claim:${c.id}`}>Claim · {c.reference}</SelectItem>)}</SelectContent></Select></Field><Field label="Document type"><Select value={documentForm.category} onValueChange={category=>setDocumentForm({...documentForm,category})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["PROPOSAL","KYC","QUOTATION","PAYMENT_EVIDENCE","INSURER_RECEIPT","POLICY_SCHEDULE","CERTIFICATE","POLICY_WORDING","CLAIM_EVIDENCE","ASSESSMENT","RENEWAL_DOCUMENT"].map(c=><SelectItem key={c} value={c}>{title(c)}</SelectItem>)}</SelectContent></Select></Field><Field label="File"><Input required type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setDocumentForm({...documentForm,file:e.target.files?.[0]??null})}/></Field></div><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={()=>setDocumentOpen(false)}>Cancel</Button><Button disabled={busy}>Upload securely</Button></DialogFooter></form></DialogContent></Dialog>
 </div>
}
type QuoteForm={fullName:string;email:string;phone:string;subjectType:string;subjectDescription:string;sumInsured:string;currency:string;coverStartDate:string;riskDetails:string;consent:boolean};
function QuoteDialog({open,setOpen,product,form,setForm,submit,busy}:{open:boolean;setOpen:(v:boolean)=>void;product:InsuranceProduct|null;form:QuoteForm;setForm:(v:QuoteForm)=>void;submit:(e:FormEvent)=>void;busy:boolean}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><form onSubmit={submit}><DialogHeader><DialogTitle>Request {product?.name}</DialogTitle><DialogDescription>Share only what an adviser needs to begin. Documents can follow later.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Full name"><Input required maxLength={160} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Phone"><Input required maxLength={40} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><Input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="What is being insured?"><Select value={form.subjectType} onValueChange={subjectType=>setForm({...form,subjectType})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{product?.subjectTypes.map(s=><SelectItem key={s} value={s}>{title(s)}</SelectItem>)}</SelectContent></Select></Field><Field label="Estimated value / sum insured"><Input type="number" min="0.01" step="0.01" value={form.sumInsured} onChange={e=>setForm({...form,sumInsured:e.target.value})}/></Field><Field label="Preferred cover start"><Input type="date" min={new Date().toISOString().slice(0,10)} value={form.coverStartDate} onChange={e=>setForm({...form,coverStartDate:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="Brief description"><Textarea required maxLength={1000} value={form.subjectDescription} onChange={e=>setForm({...form,subjectDescription:e.target.value})}/></Field></div><div className="sm:col-span-2"><Field label="Other important details (optional)"><Textarea maxLength={8000} value={form.riskDetails} onChange={e=>setForm({...form,riskDetails:e.target.value})}/></Field></div><label className="flex items-start gap-2 text-sm sm:col-span-2"><input required type="checkbox" className="mt-1" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I consent to Silverwood Insurance Agency using these details to obtain and administer insurance quotations on my behalf.</span></label></div><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy}>Submit request</Button></DialogFooter></form></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Empty({text}:{text:string}){return <div className="col-span-full flex gap-3 rounded-xl border border-dashed bg-white p-5 text-sm text-muted-foreground"><AlertCircle className="size-5 shrink-0 text-[#1769aa]"/><p>{text}</p></div>}
