// 'use client';

// import React, { useState } from 'react';
// import { useRouter } from 'next/navigation';
// import { Button } from '@/components/ui/button';
// import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
// import { cn } from '@/lib/utils';
// import { FaEnvelope, FaQrcode } from 'react-icons/fa';
// import { useAuth } from '@/hooks/useAuth';

// interface AuthMethod {
//   id: 'otp' | 'totp';
//   name: string;
//   description: string;
//   icon: React.ReactNode;
//   route: string;
// }

// interface AuthMethodSelectorProps {
//   mode: "setup" | "reset";
//   email?: string; // required for reset
// }

// const setupMethods: AuthMethod[] = [
//   {
//     id: 'otp',
//     name: 'OTP (One-Time Password)',
//     description: 'Receive a code on your email to verify your identity.',
//     icon: <FaEnvelope size={24} />,
//     route: '/otp-setup',
//   },
//   {
//     id: 'totp',
//     name: 'TOTP (Authenticator App)',
//     description: 'Use a trusted authenticator app for secure logins.',
//     icon: <FaQrcode size={24} />,
//     route: '/totp-setup',
//   },
// ];

// const resetMethods = (email: string): AuthMethod[] => [
//   {
//     id: 'otp',
//     name: 'OTP (One-Time Password)',
//     description: 'Receive a code on your email to verify your identity.',
//     icon: <FaEnvelope size={24} />,
//     route: `/reset/email?email=${email}`,
//   },
//   {
//     id: 'totp',
//     name: 'TOTP (Authenticator App)',
//     description: 'Enter the code generated by your Authenticator app.',
//     icon: <FaQrcode size={24} />,
//     route: `/reset/google?email=${email}`,
//   },
// ];

// const AuthMethodSelector: React.FC<AuthMethodSelectorProps> = ({ mode, email }) => {
//   const router = useRouter();
//   const { get_OTP } = useAuth();
//   const [selectedMethod, setSelectedMethod] = useState<AuthMethod | null>(null);

//   const methods = mode === "setup" ? setupMethods : resetMethods(email ?? "");

//   const titles = {
//     setup: {
//       heading: "Choose Your Authentication Method",
//       sub: "Enhance your account security with a second layer of verification.",
//     },
//     reset: {
//       heading: "Verify Your Identity",
//       sub: "Select a method to reset your password.",
//     },
//   };

//   const handleContinue = async () => {
//   if (!selectedMethod) return;

//   if (mode === "reset" && selectedMethod.id === "otp" && email) {
//     try {
//       const result = await get_OTP(email);
//       if (result.success) {
//         console.log("OTP sent:", result.data);
//         // then navigate to reset form
//         router.push(selectedMethod.route);
//       } else {
//         console.error("Failed to get OTP:", result.message);
//       }
//     } catch (err) {
//       console.error("Error requesting OTP:", err);
//     }
//   } else {
//     // setup mode, or reset with TOTP
//     router.push(selectedMethod.route);
//   }
// };


//   return (
//     <div className="flex flex-col items-center justify-center p-4 sm:p-8 bg-gray-50 dark:bg-gray-900 rounded-lg shadow-lg max-w-2xl mx-auto">
//       <div className="text-center mb-6">
//         <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">
//           {titles[mode].heading}
//         </h2>
//         <p className="text-gray-600 dark:text-gray-400 mt-2">
//           {titles[mode].sub}
//         </p>
//       </div>

//       <div className="grid grid-cols-1 md:grid-cols-2 gap-4 w-full mb-6">
//         {methods.map((method) => (
//           <Card
//             key={method.id}
//             className={cn(
//               "cursor-pointer transition-all duration-200 hover:shadow-lg",
//               selectedMethod?.id === method.id
//                 ? 'border-2 border-blue-500 bg-blue-50 dark:bg-blue-950'
//                 : 'border-gray-200 dark:border-gray-700'
//             )}
//             onClick={() => setSelectedMethod(method)}
//           >
//             <CardHeader className="flex flex-row items-center gap-4 space-y-0 p-4 sm:p-6">
//               <span className="text-blue-500 dark:text-blue-400">{method.icon}</span>
//               <CardTitle className="text-lg font-semibold">{method.name}</CardTitle>
//             </CardHeader>
//             <CardContent className="p-4 pt-0">
//               <CardDescription>{method.description}</CardDescription>
//             </CardContent>
//           </Card>
//         ))}
//       </div>

//       <Button
//         onClick={handleContinue}
//         disabled={!selectedMethod}
//         className="w-full sm:w-1/2 mt-4 transition-all duration-200"
//       >
//         {selectedMethod ? `Continue with ${selectedMethod.id.toUpperCase()}` : 'Select a Method to Continue'}
//       </Button>
//     </div>
//   );
// };

// export default AuthMethodSelector;
import React from 'react'

function AuthMethodSelector() {
  return (
    <div>AuthMethodSelector</div>
  )
}

export default AuthMethodSelector